using System.Reflection;
using Xunit;

namespace UniClaw.Kernel.Tests;

/// <summary>
/// RUN-003 — Kernel 公开面白名单执法：UniClaw.Kernel 程序集的公开类型
/// 集合 == 冻结名单（提升前现状 ∪ RUN-003 提升集，2026-09-20 冻结）。
/// 任何新增/移除公开类型 = RED，须经 change 显式修订本名单
/// （HOST-001 D8 裁决；EXP-008 public-shape-allowlist 先例）。
/// RUN-003 提升集（17）：KernelRunDriver / RunDriverInputs / RunDriverInput
/// （+Observation/Cancel/Unexpected）/ AgentDecisionPhase /
/// AgentDecisionContext / AgentObligationView / AgentActionProposal /
/// AgentActionStep / AgentNoActionProposal / AgentDecision（+Act/NoAction）/
/// AgentPlanPolicy / ActivationResult / RunDriveStatus / RunDriveResult
/// （嵌套类型随 FullName 计入名单）。
/// </summary>
public sealed class KernelRuntimeSurfaceWhitelistTests
{
    [Fact]
    public void PublicTypeSurface_MatchesFrozenWhitelist()
    {
        var actual = typeof(UniKernel).Assembly
            .GetExportedTypes()
            .Select(t => t.FullName!)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToArray();

        Assert.Equal(new[]
        {
            "UniClaw.Kernel.ActResult",
            "UniClaw.Kernel.Assurance.AssuranceCheck",
            "UniClaw.Kernel.Assurance.AssuranceJudgment",
            "UniClaw.Kernel.Assurance.ConsumptionRequirement",
            "UniClaw.Kernel.Assurance.FreshnessEvaluationInput",
            "UniClaw.Kernel.Assurance.FreshnessJudgment",
            "UniClaw.Kernel.Assurance.FreshnessSufficiency",
            "UniClaw.Kernel.Assurance.IFreshnessEvaluator",
            "UniClaw.Kernel.Assurance.OutcomeProof",
            "UniClaw.Kernel.Assurance.ProductFreshnessEvaluator",
            "UniClaw.Kernel.Assurance.RuntimeAssurance",
            "UniClaw.Kernel.Control.ControlDecision",
            "UniClaw.Kernel.Control.ControlInputs",
            "UniClaw.Kernel.Control.ControlIntent",
            "UniClaw.Kernel.Control.ControlIntentKind",
            "UniClaw.Kernel.Control.ControlLoop",
            "UniClaw.Kernel.Control.DescriptorTargetPolicy",
            "UniClaw.Kernel.Control.IControlPolicy",
            "UniClaw.Kernel.Control.TacticalHypothesis",
            "UniClaw.Kernel.Control.TargetSpec",
            "UniClaw.Kernel.Core.CoreSemanticProjection",
            "UniClaw.Kernel.Diagnostics.RuntimeStage",
            "UniClaw.Kernel.Diagnostics.RuntimeStageAggregate",
            "UniClaw.Kernel.Diagnostics.RuntimeStageMetrics",
            "UniClaw.Kernel.Effects.AdbEffectDriver",
            "UniClaw.Kernel.Effects.AdbLiveEffectDriver",
            "UniClaw.Kernel.Effects.BindingDecision",
            "UniClaw.Kernel.Effects.BindingRejectionReason",
            "UniClaw.Kernel.Effects.CandidateBinding",
            "UniClaw.Kernel.Effects.CanonicalBinding",
            "UniClaw.Kernel.Effects.DeliveryTarget",
            "UniClaw.Kernel.Effects.DispatchOutcome",
            "UniClaw.Kernel.Effects.DispatchOutcomePredicates",
            "UniClaw.Kernel.Effects.DispatchRequest",
            "UniClaw.Kernel.Effects.DispatchResult",
            "UniClaw.Kernel.Effects.EffectBoundary",
            "UniClaw.Kernel.Effects.EffectReceipt",
            "UniClaw.Kernel.Effects.EgoBrowserEffectDriver",
            "UniClaw.Kernel.Effects.ExecutionSource.ExecutionAttemptStatus",
            "UniClaw.Kernel.Effects.ExecutionSource.ExecutionAttemptView",
            "UniClaw.Kernel.Effects.ExecutionSource.ExecutionCommit",
            "UniClaw.Kernel.Effects.ExecutionSource.ExecutionCommitOutcome",
            "UniClaw.Kernel.Effects.ExecutionSource.ExecutionEntryKind",
            "UniClaw.Kernel.Effects.ExecutionSource.ExecutionFeedback",
            "UniClaw.Kernel.Effects.ExecutionSource.ExecutionJournalEntry",
            "UniClaw.Kernel.Effects.ExecutionSource.ExecutionLink",
            "UniClaw.Kernel.Effects.ExecutionSource.ExecutionReceiptView",
            "UniClaw.Kernel.Effects.ExecutionSource.ExecutionRegistration",
            "UniClaw.Kernel.Effects.ExecutionSource.FileExecutionJournal",
            "UniClaw.Kernel.Effects.ExecutionSource.IReliableExecutionSource",
            "UniClaw.Kernel.Effects.ExecutionSource.PendingExecution",
            "UniClaw.Kernel.Effects.GateDecision",
            "UniClaw.Kernel.Effects.IEffectDriver",
            "UniClaw.Kernel.Effects.UiTargetReference",
            "UniClaw.Kernel.Evidence.AdmissionCheck",
            "UniClaw.Kernel.Evidence.AdmissionDecision",
            "UniClaw.Kernel.Evidence.AdmissionRecord",
            "UniClaw.Kernel.Evidence.EvidenceLedger",
            "UniClaw.Kernel.Evidence.EvidenceRecord",
            "UniClaw.Kernel.Evidence.IngressKind",
            "UniClaw.Kernel.Evidence.ObservationClaim",
            "UniClaw.Kernel.Evidence.ObservationContext",
            "UniClaw.Kernel.Evidence.ObservationProposal",
            "UniClaw.Kernel.Evidence.Provenance",
            "UniClaw.Kernel.GroundedActResult",
            "UniClaw.Kernel.KernelResult",
            "UniClaw.Kernel.Outcome.RuntimeOutcome",
            "UniClaw.Kernel.Perception.AdbScreenshotAcquisition",
            "UniClaw.Kernel.Perception.ArtifactMetadata",
            "UniClaw.Kernel.Perception.ArtifactObservation",
            "UniClaw.Kernel.Perception.CapturedScreenshot",
            "UniClaw.Kernel.Perception.FastPerception",
            "UniClaw.Kernel.Perception.IFastPerceptionStrategy",
            "UniClaw.Kernel.Perception.IVersionedFastPerceptionStrategy",
            "UniClaw.Kernel.Perception.LiveVisionStrategy",
            "UniClaw.Kernel.Perception.PngImage",
            "UniClaw.Kernel.Perception.RawArtifact",
            "UniClaw.Kernel.Perception.VisionServiceClient",
            "UniClaw.Kernel.Perception.VisionServiceDiagnostic",
            "UniClaw.Kernel.Perception.VisionServiceHost",
            "UniClaw.Kernel.Perception.VisionServiceHostOptions",
            "UniClaw.Kernel.Perception.VisionServiceResult",
            "UniClaw.Kernel.Perception.VisionServiceStartupResult",
            "UniClaw.Kernel.Perception.VisionServiceTransport",
            "UniClaw.Kernel.Perception.VisionServiceTransport+LoopbackTcp",
            "UniClaw.Kernel.Perception.VisionServiceTransport+UnixDomainSocket",
            "UniClaw.Kernel.Run.ContractAdmission",
            "UniClaw.Kernel.Run.ContractCheck",
            "UniClaw.Kernel.Run.ExecutionContract",
            "UniClaw.Kernel.Run.ExecutionContractView",
            "UniClaw.Kernel.Run.ObjectiveState",
            "UniClaw.Kernel.Run.ObligationStatus",
            "UniClaw.Kernel.Run.OutcomeState",
            "UniClaw.Kernel.Run.OutcomeTransition",
            "UniClaw.Kernel.Run.ProgressState",
            "UniClaw.Kernel.Run.ProofObligationState",
            "UniClaw.Kernel.Run.RunModel",
            "UniClaw.Kernel.Run.RunObligation",
            "UniClaw.Kernel.Run.RunObligationKind",
            "UniClaw.Kernel.Run.RunState",
            "UniClaw.Kernel.Run.TerminalClassification",
            "UniClaw.Kernel.Runtime.ActivationResult",
            "UniClaw.Kernel.Runtime.AgentActionProposal",
            "UniClaw.Kernel.Runtime.AgentActionStep",
            "UniClaw.Kernel.Runtime.AgentDecision",
            "UniClaw.Kernel.Runtime.AgentDecision+Act",
            "UniClaw.Kernel.Runtime.AgentDecision+NoAction",
            "UniClaw.Kernel.Runtime.AgentDecisionContext",
            "UniClaw.Kernel.Runtime.AgentDecisionPhase",
            "UniClaw.Kernel.Runtime.AgentNoActionProposal",
            "UniClaw.Kernel.Runtime.AgentObligationView",
            "UniClaw.Kernel.Runtime.AgentPlanPolicy",
            "UniClaw.Kernel.Runtime.KernelRunDriver",
            "UniClaw.Kernel.Runtime.RunDriveResult",
            "UniClaw.Kernel.Runtime.RunDriveStatus",
            "UniClaw.Kernel.Runtime.RunDriverInput",
            "UniClaw.Kernel.Runtime.RunDriverInput+Cancel",
            "UniClaw.Kernel.Runtime.RunDriverInput+Observation",
            "UniClaw.Kernel.Runtime.RunDriverInput+Unexpected",
            "UniClaw.Kernel.Runtime.RunDriverInputs",
            "UniClaw.Kernel.TerminalEvaluation",
            "UniClaw.Kernel.Trace.DisabledRunTrace",
            "UniClaw.Kernel.Trace.IRunTrace",
            "UniClaw.Kernel.Trace.ITraceOperationScope",
            "UniClaw.Kernel.Trace.RecorderTerminal",
            "UniClaw.Kernel.Trace.RunCorrelation",
            "UniClaw.Kernel.Trace.RunTraceArtifact",
            "UniClaw.Kernel.Trace.RunTraceFactory",
            "UniClaw.Kernel.Trace.RunTraceScope",
            "UniClaw.Kernel.Trace.SpanDefinition",
            "UniClaw.Kernel.Trace.StructuralOutcome",
            "UniClaw.Kernel.Trace.TraceCatalog",
            "UniClaw.Kernel.Trace.TraceContext",
            "UniClaw.Kernel.Trace.TraceDiagnostic",
            "UniClaw.Kernel.Trace.TraceEvent",
            "UniClaw.Kernel.Trace.TraceEventDefinition",
            "UniClaw.Kernel.Trace.TraceReference",
            "UniClaw.Kernel.Trace.TraceReferenceKind",
            "UniClaw.Kernel.Trace.TraceSpan",
            "UniClaw.Kernel.UniKernel",
            "UniClaw.Kernel.World.ActionAssuranceView",
            "UniClaw.Kernel.World.BindingView",
            "UniClaw.Kernel.World.ClaimEvolutionDecision",
            "UniClaw.Kernel.World.ClaimEvolutionKind",
            "UniClaw.Kernel.World.Conflict",
            "UniClaw.Kernel.World.EntityObligationFact",
            "UniClaw.Kernel.World.EntityObligationFactKind",
            "UniClaw.Kernel.World.FreshnessBasis",
            "UniClaw.Kernel.World.NativeLocator",
            "UniClaw.Kernel.World.OccurrenceFact",
            "UniClaw.Kernel.World.OutcomeAssuranceView",
            "UniClaw.Kernel.World.RelevanceJudgment",
            "UniClaw.Kernel.World.ScopedClaim",
            "UniClaw.Kernel.World.Slice",
            "UniClaw.Kernel.World.SpatialLocator",
            "UniClaw.Kernel.World.TransitionContext",
            "UniClaw.Kernel.World.TransitionStrength",
            "UniClaw.Kernel.World.UiRealization.AssociationCandidate",
            "UniClaw.Kernel.World.UiRealization.AssociationDecision",
            "UniClaw.Kernel.World.UiRealization.AssociationDispositionKind",
            "UniClaw.Kernel.World.UiRealization.AssociationInput",
            "UniClaw.Kernel.World.UiRealization.AssociationProposal",
            "UniClaw.Kernel.World.UiRealization.CandidateOccurrenceFact",
            "UniClaw.Kernel.World.UiRealization.ContainerBelief",
            "UniClaw.Kernel.World.UiRealization.ContainerIdentity",
            "UniClaw.Kernel.World.UiRealization.ContainerRelation",
            "UniClaw.Kernel.World.UiRealization.ContainerRelationKind",
            "UniClaw.Kernel.World.UiRealization.ContinuityAdjudicationInput",
            "UniClaw.Kernel.World.UiRealization.ContinuityAdjudicationOutcomeKind",
            "UniClaw.Kernel.World.UiRealization.ContinuityCandidateItem",
            "UniClaw.Kernel.World.UiRealization.ContinuityCandidateOccurrence",
            "UniClaw.Kernel.World.UiRealization.ContinuityDecision",
            "UniClaw.Kernel.World.UiRealization.ContinuityDemand",
            "UniClaw.Kernel.World.UiRealization.ContinuityDemandSourceKind",
            "UniClaw.Kernel.World.UiRealization.ContinuityProposal",
            "UniClaw.Kernel.World.UiRealization.ContinuityProposedOutcomeKind",
            "UniClaw.Kernel.World.UiRealization.ContinuityResolution",
            "UniClaw.Kernel.World.UiRealization.ContinuityResolutionOutcome",
            "UniClaw.Kernel.World.UiRealization.ContinuityResolutionOutcomeKind",
            "UniClaw.Kernel.World.UiRealization.CurrentCandidateSetResultKind",
            "UniClaw.Kernel.World.UiRealization.CurrentGroundingView",
            "UniClaw.Kernel.World.UiRealization.DemandHandle",
            "UniClaw.Kernel.World.UiRealization.IAssociationStrategy",
            "UniClaw.Kernel.World.UiRealization.IContinuityStrategy",
            "UniClaw.Kernel.World.UiRealization.IUiObservationStrategy",
            "UniClaw.Kernel.World.UiRealization.LogicalItemBelief",
            "UniClaw.Kernel.World.UiRealization.LogicalItemLifecycle",
            "UniClaw.Kernel.World.UiRealization.OccurrenceBelief",
            "UniClaw.Kernel.World.UiRealization.ProposedOccurrence",
            "UniClaw.Kernel.World.UiRealization.ProposedRelation",
            "UniClaw.Kernel.World.UiRealization.ProposedTermination",
            "UniClaw.Kernel.World.UiRealization.TargetDescriptor",
            "UniClaw.Kernel.World.Uncertainty",
            "UniClaw.Kernel.World.WorldBeliefRevision",
            "UniClaw.Kernel.World.WorldClaim",
            "UniClaw.Kernel.World.WorldModel"
        }, actual);
    }
}
