#!/usr/bin/env python3
"""从 run.log 或 trace.jsonl 提取 FSM 状态转移序列，生成 ASCII 转移链和状态频次直方图。

用法:
  python3 fsm_transition_path.py --run <runDir>            # 自动定位 run.log 或 trace.jsonl
  python3 fsm_transition_path.py --log <run.log>            # 从 run.log 提取
  python3 fsm_transition_path.py --trace <trace.jsonl>      # 从 trace.jsonl 提取
  python3 fsm_transition_path.py --log <run.log> --validate # 验证每条转移是否合法（对照内嵌矩阵）
  python3 fsm_transition_path.py --log <run.log> --json     # JSON 输出（机器可读）

输入格式:
  run.log:  [HH:mm:ss.fff] [t=<runId>] [s=<spanId>] [LEVEL] Category: message
            其中 FSM 转移行: "FSM {From}→{To} step={Step}"
  trace.jsonl: 每行 JSON，record_type=="StateTransition" 的记录提取 FromState/ToState

输出:
  - ASCII 转移链（带 step 编号和时间戳）
  - 状态频次直方图
  - --validate 模式：标注非法转移
  - --json 模式：结构化 JSON

退出码: 0=成功, 1=未找到 FSM 转移, 2=用法错误/文件不存在
"""

import argparse
import json
import os
import re
import sys
from collections import Counter
from pathlib import Path

# ---------------------------------------------------------------------------
# TraversalFSM transition matrix
# Prefer --matrix-from-source (pulls from C# source = always current).
# The hardcoded fallback is auto-generated by matrix_from_source.py — if stale,
# run: python3 matrix_from_source.py --python  to update.
# ---------------------------------------------------------------------------

def _load_matrix_from_source() -> dict[str, set[str]]:
    """Run matrix_from_source.py --json and return TraversalFSM matrix as {from: {to}}."""
    import subprocess
    script_dir = Path(__file__).resolve().parent
    matrix_script = script_dir / "matrix_from_source.py"
    try:
        result = subprocess.run(
            [sys.executable, str(matrix_script), "--fsm", "traversal", "--json"],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0:
            data = json.loads(result.stdout)
            return {k: set(v) for k, v in data.items()}
    except (subprocess.TimeoutExpired, json.JSONDecodeError, FileNotFoundError, OSError):
        pass
    return _FALLBACK_MATRIX  # Use hardcoded fallback on any failure


# Hardcoded fallback — update with: matrix_from_source.py --python
_FALLBACK_MATRIX: dict[str, set[str]] = {
    "NodeSelect":        {"PreconditionCheck", "Branch"},
    "PreconditionCheck": {"Execute", "ErrorHandling"},
    "Execute":           {"ResultVerify", "Branch", "ErrorHandling"},
    "ResultVerify":      {"Branch", "PopupHandling", "ErrorHandling"},
    "Branch":            {"NodeSelect", "PreconditionCheck", "FrameComplete", "ErrorHandling"},
    "FrameComplete":     {"NodeSelect", "ErrorHandling"},
    "ErrorHandling":     {"NodeSelect", "Execute", "FrameComplete", "Branch"},
    "PopupHandling":     {"ResultVerify", "ErrorHandling"},
}

# ---------------------------------------------------------------------------
# Parsers
# ---------------------------------------------------------------------------

# Same regex as scripts/log-analyzer.py for consistency
LOG_RE = re.compile(
    r"\[(?P<time>[^\]]+)\] \[t=(?P<trace>[^\]]*)\] \[s=(?P<span>[^\]]*)\] "
    r"\[(?P<level>\w+\s*)\] (?P<category>\S+): (?P<msg>.+)"
)
FSM_RE = re.compile(r"FSM (?P<from>\w+)→(?P<to>\w+) step=(?P<step>\d+)")


def parse_runlog(path: str) -> list[dict]:
    """Extract FSM transitions from a run.log file."""
    transitions = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            lm = LOG_RE.match(line)
            if not lm:
                continue
            d = lm.groupdict()
            fm = FSM_RE.match(d["msg"])
            if not fm:
                continue
            fd = fm.groupdict()
            transitions.append({
                "time": d["time"],
                "span_id": d["span"],
                "level": d["level"].strip(),
                "from_state": fd["from"],
                "to_state": fd["to"],
                "step": int(fd["step"]),
            })
    return transitions


def parse_trace_jsonl(path: str) -> list[dict]:
    """Extract FSM transitions from a trace.jsonl file (StateTransition records)."""
    transitions = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            rt = rec.get("record_type", "")
            if rt in ("StateTransition", "state_transition"):
                transitions.append({
                    "time": rec.get("timestamp", rec.get("time", "")),
                    "span_id": rec.get("span_id", rec.get("spanId", "")),
                    "from_state": rec.get("from_state", rec.get("fromState", rec.get("FromState", ""))),
                    "to_state": rec.get("to_state", rec.get("toState", rec.get("ToState", ""))),
                    "step": rec.get("step", rec.get("step_number", rec.get("StepNumber", 0))),
                })
            # Also catch legacy format: span with FSM metadata
            elif rt == "span" and "FromState" in rec:
                transitions.append({
                    "time": rec.get("timestamp", ""),
                    "span_id": rec.get("span_id", rec.get("spanId", "")),
                    "from_state": rec.get("FromState", ""),
                    "to_state": rec.get("ToState", ""),
                    "step": rec.get("StepNumber", 0),
                })
    return transitions


def resolve_input(run_dir: str | None, log_path: str | None, trace_path: str | None) -> list[dict]:
    """Resolve input to a list of transitions. Tries run.log first, then trace.jsonl."""
    if log_path:
        return parse_runlog(log_path)
    if trace_path:
        return parse_trace_jsonl(trace_path)
    if run_dir:
        p = Path(run_dir)
        # Try V2 layout: trace/{runId}/run.log
        runlog_candidates = list(p.rglob("run.log"))
        for cand in runlog_candidates:
            result = parse_runlog(str(cand))
            if result:
                return result
        # Try trace.jsonl
        trace_candidates = list(p.rglob("trace.jsonl"))
        for cand in trace_candidates:
            result = parse_trace_jsonl(str(cand))
            if result:
                return result
    return []


# ---------------------------------------------------------------------------
# Output formatters
# ---------------------------------------------------------------------------

def format_chain(transitions: list[dict], validate: bool = False,
                 matrix: dict[str, set[str]] | None = None) -> str:
    """Build ASCII transition chain."""
    if not transitions:
        return "(no FSM transitions found)"

    if validate and matrix is None:
        matrix = _load_matrix_from_source()

    lines = []
    # Header
    lines.append("FSM Transition Path")
    if validate and matrix:
        lines.append("(validated against live C# source matrix)")
    lines.append("=" * 80)

    # Chain
    states = [transitions[0]["from_state"]]
    for i, t in enumerate(transitions):
        states.append(t["to_state"])
        valid = ""
        if validate and matrix:
            legal = t["to_state"] in matrix.get(t["from_state"], set())
            if not legal:
                valid = " ⚠ ILLEGAL"
        time_str = t.get("time", "")[:12] if t.get("time") else ""
        lines.append(
            f"  step {t['step']:>4d}  {t['from_state']:>16s} → {t['to_state']:<16s}"
            f"  {time_str}{valid}"
        )

    lines.append("")
    lines.append(f"Total: {len(transitions)} transitions, {len(set(states))} unique states")
    return "\n".join(lines)


def format_histogram(transitions: list[dict]) -> str:
    """Build state frequency histogram."""
    if not transitions:
        return ""

    from_counts = Counter(t["from_state"] for t in transitions)
    to_counts = Counter(t["to_state"] for t in transitions)

    all_states = sorted(set(list(from_counts) + list(to_counts)))
    max_count = max(max(from_counts.values()), max(to_counts.values())) if from_counts else 0
    bar_width = 30

    lines = ["", "State Frequency Histogram", "=" * 80]
    lines.append(f"{'State':<20s} {'Visited (from)':>10s} {'Entered (to)':>10s}  {'':{bar_width}s}")
    lines.append("-" * 80)

    for s in all_states:
        fc = from_counts.get(s, 0)
        tc = to_counts.get(s, 0)
        bar_from = "█" * int(fc / max(max_count, 1) * bar_width) if max_count else ""
        bar_to = "▓" * int(tc / max(max_count, 1) * bar_width) if max_count else ""
        lines.append(f"{s:<20s} {fc:>4d} {bar_from:<{bar_width}s} {tc:>4d} {bar_to}")

    return "\n".join(lines)


def format_json_output(transitions: list[dict]) -> str:
    """JSON structured output."""
    return json.dumps({
        "total_transitions": len(transitions),
        "transitions": [
            {
                "step": t["step"],
                "from": t["from_state"],
                "to": t["to_state"],
                "time": t.get("time", ""),
                "span_id": t.get("span_id", ""),
            }
            for t in transitions
        ],
        "state_frequency": {
            "from": dict(Counter(t["from_state"] for t in transitions)),
            "to": dict(Counter(t["to_state"] for t in transitions)),
        },
    }, indent=2)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Extract FSM transition paths from run.log or trace.jsonl",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --run artifacts/runs/scenario/run-id
  %(prog)s --log trace/run-id/run.log --validate
  %(prog)s --trace trace/run-id/trace.jsonl --json
  %(prog)s --log trace/run-id/run.log --validate --matrix-file matrix.json
        """,
    )
    parser.add_argument("--run", help="Run directory (auto-locates run.log or trace.jsonl)")
    parser.add_argument("--log", help="Path to run.log file")
    parser.add_argument("--trace", help="Path to trace.jsonl file")
    parser.add_argument("--validate", action="store_true",
                        help="Validate each transition against the TraversalFSM matrix "
                             "(auto-extracts from C# source via matrix_from_source.py)")
    parser.add_argument("--matrix-file",
                        help="Path to cached matrix JSON (from matrix_from_source.py --json). "
                             "Skips source extraction for faster repeated runs.")
    parser.add_argument("--json", dest="json_out", action="store_true",
                        help="Output as JSON (machine-readable)")

    args = parser.parse_args()

    if not args.run and not args.log and not args.trace:
        parser.error("One of --run, --log, or --trace is required")

    # Load matrix for validation
    matrix = None
    if args.validate:
        if args.matrix_file:
            try:
                data = json.loads(Path(args.matrix_file).read_text())
                # Handle both wrapped JSON (matrix_from_source.py --json)
                # and raw matrix dict (matrix_from_source.py --fsm traversal --json)
                raw = data
                if isinstance(data, dict):
                    # Wrapped: {"traversal_fsm": {"matrix": {...}}, ...}
                    if "traversal_fsm" in data:
                        raw = data["traversal_fsm"]["matrix"]
                    elif "matrix" in data:
                        raw = data["matrix"]
                matrix = {k: set(v) for k, v in raw.items()}
            except (json.JSONDecodeError, FileNotFoundError, OSError) as e:
                print(f"Warning: cannot load --matrix-file: {e}; falling back to source", file=sys.stderr)
        if matrix is None:
            matrix = _load_matrix_from_source()

    transitions = resolve_input(args.run, args.log, args.trace)

    if not transitions:
        print("No FSM transitions found in input.", file=sys.stderr)
        sys.exit(1)

    if args.json_out:
        print(format_json_output(transitions))
    else:
        print(format_chain(transitions, validate=args.validate, matrix=matrix))
        print(format_histogram(transitions))

    sys.exit(0)


if __name__ == "__main__":
    main()
