using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace UniClaw.Core.SourceGen
{
    /// <summary>
    /// Emitter — generates partial class async wrapper methods for [TraceHandler]-decorated handlers.
    /// Includes auto-extracted metadata (null skip, enum→string, [TraceIgnore] exclusion),
    /// extraMetadata merge, PushSpan/PopSpan try/finally, and exception handling.
    ///
    /// Generated wrapper signature:
    ///   public async Task&lt;ReturnType&gt; MethodNameTracedAsync(
    ///       params...,                              // original parameters
    ///       IHandlerTraceWriter? handlerTrace = null,
    ///       ITraceCoordinator? trace = null,         // for PushSpan/PopSpan
    ///       Dictionary&lt;string, object&gt;? extraMetadata = null)
    /// </summary>
    internal static class Emitter
    {
        /// <summary>
        /// Generate the full partial class wrapper source for a [TraceHandler] method.
        /// </summary>
        public static string GenerateWrapper(TraceHandlerGenerator.TraceHandlerMethodInfo method)
        {
            var sb = new StringBuilder();
            var returnType = method.ReturnType;

            // Determine status expression from return type
            string statusExpr = returnType switch
            {
                var t when t.Contains("ErrorRecoveryResult") => "result.Outcome == RecoveryOutcome.Success ? \"success\" : \"fail\"",
                var t when t.Contains("PopupHandlingResult") => "result.Success ? \"success\" : \"fail\"",
                var t when t.Contains("ContainerActionResult") => "result.Success ? \"success\" : \"fail\"",
                _ => "\"ok\""
            };

            // ── Header ──
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable CS1591");
            sb.AppendLine();
            sb.AppendLine($"namespace {method.ClassNamespace};");
            sb.AppendLine();
            sb.AppendLine($"partial class {method.ClassName}");
            sb.AppendLine("{");

            // ── Wrapper method signature ──
            var wrapperName = $"{method.MethodName}TracedAsync";
            sb.Append("    public async global::System.Threading.Tasks.Task<");
            sb.Append(returnType);
            sb.Append("> ");
            sb.Append(wrapperName);
            sb.AppendLine("(");

            // Original parameters
            for (int i = 0; i < method.Parameters.Count; i++)
            {
                var p = method.Parameters[i];
                sb.Append($"        {p.type} {p.name}");
                sb.AppendLine(",");
            }

            // Additional trace parameters
            sb.AppendLine("        global::UniClaw.Core.Observability.IHandlerTraceWriter? handlerTrace = null,");
            sb.AppendLine("        global::UniClaw.Core.Traversal.ITraceCoordinator? trace = null,");
            sb.AppendLine("        System.Collections.Generic.Dictionary<string, object>? extraMetadata = null)");

            // ── Method body ──
            sb.AppendLine("    {");

            // PushSpan
            sb.AppendLine("        string? _spanId = null;");
            sb.AppendLine("        if (trace != null)");
            sb.AppendLine("            _spanId = trace.PushSpan();");
            sb.AppendLine();

            // try block
            sb.AppendLine("        try");
            sb.AppendLine("        {");

            // Call original method
            var paramNames = string.Join(", ", method.Parameters.Select(p => p.name));
            sb.AppendLine($"            var result = {method.MethodName}({paramNames});");

            // Record lifecycle on success
            sb.AppendLine("            if (handlerTrace != null)");
            sb.AppendLine("            {");
            sb.AppendLine("                var meta = new System.Collections.Generic.Dictionary<string, object>();");

            // Auto-extract properties (based on known return type schemas)
            foreach (var prop in GetPropertyExtraction(method.ReturnType))
            {
                if (prop.IsIgnored)
                    continue;

                var keyName = ToSnakeCase(prop.Name);
                var propAccess = $"result.{prop.Name}";

                if (prop.IsNullable)
                {
                    sb.AppendLine($"                if ({propAccess} != null)");
                    if (prop.IsEnum)
                        sb.AppendLine($"                    meta[\"{keyName}\"] = {propAccess}.ToString()!;");
                    else
                        sb.AppendLine($"                    meta[\"{keyName}\"] = {propAccess};");
                }
                else
                {
                    if (prop.IsEnum)
                        sb.AppendLine($"                meta[\"{keyName}\"] = {propAccess}.ToString();");
                    else if (prop.TypeName == "double")
                        sb.AppendLine($"                meta[\"{keyName}\"] = (double){propAccess};");
                    else
                        sb.AppendLine($"                meta[\"{keyName}\"] = {propAccess};");
                }
            }

            // extraMetadata merge
            sb.AppendLine("                if (extraMetadata != null)");
            sb.AppendLine("                    foreach (var kv in extraMetadata)");
            sb.AppendLine("                        meta[kv.Key] = kv.Value;");

            // Build TraceContext from trace coordinator
            sb.AppendLine("                var _context = trace?.BuildCorrelation();");

            // RecordHandlerLifecycleAsync call
            sb.AppendLine();
            var actionValue = Unquote(method.ActionArg);
            var spanTypeValue = method.SpanTypeArg.Replace("SpanType.", "").Trim();
            sb.AppendLine($"                await handlerTrace.RecordHandlerLifecycleAsync(");
            sb.AppendLine($"                    \"{actionValue}\",");
            sb.AppendLine($"                    global::UniClaw.Core.Observability.SpanType.{spanTypeValue},");
            sb.AppendLine($"                    {statusExpr},");
            sb.AppendLine($"                    meta,");
            sb.AppendLine($"                    _context);");

            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return result;");
            sb.AppendLine("        }");

            // Catch — exception handling with fail status
            sb.AppendLine("        catch (global::System.Exception ex)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (handlerTrace != null)");
            sb.AppendLine("            {");
            sb.AppendLine("                var exMeta = new System.Collections.Generic.Dictionary<string, object>");
            sb.AppendLine("                {");
            sb.AppendLine("                    [\"exception\"] = ex.GetType().Name,");
            sb.AppendLine("                    [\"exception_message\"] = ex.Message");
            sb.AppendLine("                };");
            sb.AppendLine("                var _exContext = trace?.BuildCorrelation();");
            sb.AppendLine("                await handlerTrace.RecordHandlerLifecycleAsync(");
            sb.AppendLine($"                    \"{actionValue}\",");
            sb.AppendLine($"                    global::UniClaw.Core.Observability.SpanType.{spanTypeValue},");
            sb.AppendLine("                    \"fail\", exMeta, _exContext);");
            sb.AppendLine("            }");
            sb.AppendLine("            throw;");
            sb.AppendLine("        }");

            // finally — PopSpan
            sb.AppendLine("        finally");
            sb.AppendLine("        {");
            sb.AppendLine("            if (trace != null && _spanId != null)");
            sb.AppendLine("                trace.PopSpan(_spanId);");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("#pragma warning restore CS1591");

            return sb.ToString();
        }

        // ── Property schema definitions for known return types ──

        internal sealed record class PropertyInfo(
            string Name, string TypeName, bool IsEnum, bool IsNullable, bool IsIgnored);

        /// <summary>
        /// Generate property extraction info based on known return types.
        /// Each entry maps a return type to its readable properties with metadata hints.
        /// </summary>
        private static List<PropertyInfo> GetPropertyExtraction(string returnType)
        {
            if (returnType.Contains("ErrorRecoveryResult"))
            {
                return new()
                {
                    new("Strategy", "ErrorStrategy", IsEnum: true, IsNullable: false, IsIgnored: false),
                    new("Outcome", "RecoveryOutcome", IsEnum: true, IsNullable: false, IsIgnored: false),
                    new("BackoffDelaySeconds", "double", IsEnum: false, IsNullable: false, IsIgnored: false),
                    new("Description", "string?", IsEnum: false, IsNullable: true, IsIgnored: false),
                };
            }

            if (returnType.Contains("PopupHandlingResult"))
            {
                return new()
                {
                    new("Success", "bool", IsEnum: false, IsNullable: false, IsIgnored: false),
                    new("Action", "string", IsEnum: false, IsNullable: false, IsIgnored: false),
                    new("Description", "string", IsEnum: false, IsNullable: false, IsIgnored: false),
                    new("Classification", "PopupClassification?", IsEnum: false, IsNullable: true, IsIgnored: true),
                };
            }

            if (returnType.Contains("ContainerActionResult"))
            {
                return new()
                {
                    new("Action", "FallbackAction", IsEnum: true, IsNullable: false, IsIgnored: false),
                    new("Success", "bool", IsEnum: false, IsNullable: false, IsIgnored: false),
                    new("Description", "string", IsEnum: false, IsNullable: false, IsIgnored: false),
                    new("CompletionReason", "CompletionReason?", IsEnum: false, IsNullable: true, IsIgnored: false),
                    new("TotalChildren", "int?", IsEnum: false, IsNullable: true, IsIgnored: false),
                    new("VisitedChildCount", "int?", IsEnum: false, IsNullable: true, IsIgnored: false),
                    new("Depth", "int?", IsEnum: false, IsNullable: true, IsIgnored: false),
                };
            }

            return new();
        }

        private static string ToSnakeCase(string name)
        {
            if (string.IsNullOrEmpty(name)) return name;
            var sb = new StringBuilder();
            for (int i = 0; i < name.Length; i++)
            {
                if (char.IsUpper(name[i]))
                {
                    if (i > 0) sb.Append('_');
                    sb.Append(char.ToLowerInvariant(name[i]));
                }
                else
                {
                    sb.Append(name[i]);
                }
            }
            return sb.ToString();
        }

        private static string Unquote(string value)
        {
            if (value.Length >= 2 && value[0] == '"' && value[value.Length - 1] == '"')
                return value.Substring(1, value.Length - 2).Replace("\\\"", "\"");
            return value;
        }
    }
}
