// Generated by ProductProtocolSchemaGenerator. DO NOT EDIT.

export type AgentActionProposal = { decisionId: string; justification?: string; steps: Array<AgentActionStep> };
export type AgentActionStep = { desiredState?: string; effectClass: string; targetDescriptor?: string; targetRole: string };
export type AgentDecision = { decisionId: string; kind: 'act'; proposal: AgentActionProposal } | { decisionId: string; kind: 'policy'; proposal: PolicyProposal } | { decisionId: string; kind: 'noAction'; proposal: AgentNoActionProposal } | { decisionId: string; kind: 'defer'; spec: ObserveSpec };
export type AgentDecisionContext = { allowedEffects: Array<string>; budgetRemaining?: ConsultationBudget; contractVersion: string; currentWorldClaims: { [key: string]: ClaimSummary }; decisionId: string; elements?: Array<ElementSummary>; failedStepIndex?: number; failureReason?: string; objective: string; pendingObligations: Array<AgentObligationView>; phase: 'DeferRoundsExhausted' | 'InitialPlanning' | 'PolicyInvalidated' | 'StepRejected' | 'StepVerified' | 'VerificationFailed'; progress?: ConsultationProgress; runId: string; screen?: ScreenSummary };
export type AgentNoActionProposal = { completion?: CompletionEvidence; decisionId: string; justification: string };
export type AgentObligationView = { kind: string; mandatory: boolean; obligationId: string; requiredValue: string; subject: string };
export type ClaimSummary = { disposition: string; inConflict: boolean; value: string };
export type CompletionEvidence = { basis: string; checklist: Array<string> };
export type ConsultationBudget = { roundsRemaining: number; stepsRemaining: number };
export type ConsultationProgress = { policyState?: PolicyProgressState; roundsUsed: number; stepsDispatched: number; stepsVerified: number };
export type ElementSummary = { bounds?: string; checkable?: boolean; clickable?: boolean; enabled?: boolean; epistemic: 'Ambiguous' | 'Observed' | 'Partial'; role: string; text?: string };
export type ObserveSpec = { maxRounds: number; subject?: string };
export type PolicyActionTemplate = { desiredState?: string; effectClass: string; targetDescriptor?: string; targetRole: string };
export type PolicyGuard = { afterRounds: number; kind: 'observationUnchanged'; subject: string };
export type PolicyPredicate = { kind: 'claimEquals'; subject: string; value: string } | { kind: 'claimInSet'; subject: string; values: Array<string> };
export type PolicyProgressState = { applicationsUsed: number; policyId: string; terminationStatus: 'Satisfied' | 'Unknown' | 'Violated' };
export type PolicyProposal = { actionTemplate: PolicyActionTemplate; guards: Array<PolicyGuard>; justification?: string; match: Array<PolicyPredicate>; maxApplications: number; policyId: string; termination: Array<PolicyPredicate> };
export type ScreenSummary = { containerId: string; signature?: string };
export type SubmitDecision = { decision: AgentDecision };
export type ProductProtocolEnvelope = { agentDecision?: AgentDecision; agentDecisionContext?: AgentDecisionContext; protocolVersion: 'uniclaw.agent.protocol.v1'; schemaVersion: 'uniclaw.agent.schema.v1'; submit_decision?: { decision: AgentDecision } };
