<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>UniClaw.Host</RootNamespace>
    <AssemblyName>UniClaw.Host</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UniClaw.ClaudeProvider\UniClaw.ClaudeProvider.csproj" />
    <ProjectReference Include="..\UniClaw.Core\UniClaw.Core.csproj" />
    <ProjectReference Include="..\UniClaw.DeepSeekProvider\UniClaw.DeepSeekProvider.csproj" />
    <ProjectReference Include="..\UniClaw.Device\UniClaw.Device.csproj" />
  </ItemGroup>

</Project>
