using System.Collections.Immutable;
using UniClaw.Semantic.Infrastructure.Corpus;
using UniClaw.Runtime.Model;

namespace UniClaw.Semantic.Tests.BenchmarkTests;

/// <summary>
/// ContainerIdentity-heldout-v2 — TRUE independent held-out corpus for the
/// qualification gate PROJECT_LEADER_SEMANTIC_PROFILE_V2_HELD_OUT_QUALIFICATION.
///
/// HYGIENE CONTRACT (this corpus qualifies Profile V2, it does not tune it):
/// - Created AFTER Profile V2 was frozen (profile hash at creation is bound in
///   the manifest / qualification receipt; Profile V2 file is NOT modified by
///   this gate).
/// - Did NOT participate in feature/embedding/prototype/margin/evidence-
///   sufficiency/anchor/policy design or in V1/V2 debugging / safety hardening.
/// - NOT derived from former-heldout-v1 failure instances: new wordings, new
///   observation combinations, new visibility states, new hard-negative
///   patterns. Failure CATEGORIES (wrong page, text overlap, generic settings
///   page, near-empty, structural similarity, sibling container, conflicting
///   previous identity) are reused; concrete instances are fresh.
/// - If (and only if) this corpus is ever used for DESIGN, it loses held-out
///   identity (see gate §23).
///
/// Scope: 64 cases = 4 identities × 10 positive states
///   (Normal/title-visible ×2, title-offscren scroll ×2, scroll-bottom,
///    partial ×2, scroll+switch, reworded wording, full-combo)
///   + 24 negatives/hard negatives (6 per identity: wrong page, text-overlap,
///    generic settings page, near-empty, structurally similar wrong identity,
///    semantically similar sibling container / conflicting previous identity).
///
/// Sources: RealTrace (verbatim contiguous subsets of the captured
/// root-scrolled frame in
/// openspec/.../uitars-bench/truth.json — NEW subsets not used by heldout-v1),
/// Manual (composed from real Settings-app vocabulary, fresh combinations),
/// Synthetic (independent adversarial constructions).
/// </summary>
public static class HeldOutContainerIdentityCorpusV2
{
    /// <summary>Held-out v2 corpus identity.</summary>
    public const string CorpusId = "ContainerIdentity-heldout-v2";

    private static readonly string[] RootScrollRealTraceFragment =
    {
        "Search settings", "Battery", "100%", "Storage", "Sound & vibration",
        "Display", "Wallpaper", "Home, lock screen", "Accessibility",
    };

    private static Observation Obs(long seq, params ObservedElement[] elements) =>
        new(elements.ToImmutableArray(), "com.android.settings", seq);

    private static ObservedElement El(string text, int index, string? type = null, bool? switchState = null) =>
        new(text, switchState, index, null, type);

    private static SemanticCase Case(
        string caseId,
        long seq,
        string expectedCandidate,
        string? expectedIdentity,
        SemanticCaseSource source,
        SemanticCaseDifficulty difficulty,
        SemanticViewportState viewport,
        int ambiguity,
        double scroll,
        string? previousVerifiedIdentity,
        params ObservedElement[] elements) =>
        new(
            caseId,
            Obs(seq, elements),
            expectedCandidate,
            expectedIdentity,
            source,
            difficulty)
        {
            PreviousVerifiedIdentity = previousVerifiedIdentity,
            ViewportState = viewport,
            VisibleAnchorState = viewport == SemanticViewportState.TitleVisible
                ? SemanticVisibleAnchorState.AnchorVisible
                : SemanticVisibleAnchorState.AnchorMissing,
            NoiseLevel = difficulty == SemanticCaseDifficulty.Hard ? 1 : 0,
            AmbiguityLevel = ambiguity,
            ScrollPosition = scroll,
        };

    /// <summary>Creates the v2 held-out corpus.</summary>
    public static SemanticCorpus Create() => Build();

    private static SemanticCorpus Build()
    {
        var cases = ImmutableArray.Create(
            // ── DeveloperOptions ───────────────────────────────────────────────
            Case("ho2-dev-P1", 1, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "DeveloperOptions",
                El("Developer options", 0, "text"),
                El("Wireless debugging", 1, "menu_item"),
                El("USB debugging", 2, "menu_item")),
            Case("ho2-dev-P2", 2, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "DeveloperOptions",
                El("Developer options", 0, "text"),
                El("Select USB configuration", 1, "menu_item"),
                El("OEM unlocking", 2, "menu_item")),
            Case("ho2-dev-P3", 3, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.45, "DeveloperOptions",
                El("Wireless debugging", 0, "menu_item"),
                El("USB debugging", 1, "menu_item"),
                El("Enable demo mode", 2, "switch", true)),
            Case("ho2-dev-P4", 4, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.9, "DeveloperOptions",
                El("Show touch data", 0, "switch", false),
                El("Display refresh rate", 1, "menu_item"),
                El("OEM unlocking", 2, "menu_item")),
            Case("ho2-dev-P5", 5, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, 0, 0.6, "DeveloperOptions",
                El("USB debugging", 0, "menu_item"),
                El("OEM unlocking", 1, "menu_item")),
            Case("ho2-dev-P6", 6, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, 1, 0.5, "DeveloperOptions",
                El("Enable demo mode", 0, "switch", true)),
            Case("ho2-dev-P7", 7, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.7, "DeveloperOptions",
                El("Automatic system updates", 0, "switch", true),
                El("Background process limit", 1, "menu_item"),
                El("Show taps", 2, "menu_item")),
            Case("ho2-dev-P8", 8, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 1, 0, "DeveloperOptions",
                El("Developer options", 0, "text"),
                El("Enable Wi‑Fi verbose logging", 1, "menu_item"),
                El("Displays in log viewer", 2, "text_block")),
            Case("ho2-dev-P9", 9, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.3, "DeveloperOptions",
                El("Show taps", 0, "switch", false),
                El("Pointer location", 1, "switch", false)),
            Case("ho2-dev-P10", 10, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "DeveloperOptions",
                El("Developer options", 0, "text"),
                El("USB debugging", 1, "menu_item"),
                El("Automatic system updates", 2, "switch", true),
                El("OEM unlocking", 3, "menu_item")),
            // ── WifiSettings ──────────────────────────────────────────────────
            Case("ho2-wifi-P1", 11, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "WifiSettings",
                El("Wi‑Fi", 0, "menu_item"),
                El("Wi‑Fi calling", 1, "menu_item"),
                El("Wi‑Fi Direct", 2, "menu_item")),
            Case("ho2-wifi-P2", 12, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "WifiSettings",
                El("Wi‑Fi", 0, "text"),
                El("Connected", 1, "text_block"),
                El("AndroidWifi", 2, "text_block"),
                El("Wi‑Fi Direct", 3, "menu_item")),
            Case("ho2-wifi-P3", 13, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.5, "WifiSettings",
                El("AndroidWifi", 0, "text_block"),
                El("Wi‑Fi calling", 1, "menu_item"),
                El("Network speed", 2, "text_block")),
            Case("ho2-wifi-P4", 14, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.95, "WifiSettings",
                El("Wi‑Fi Direct", 0, "switch", false),
                El("Install certificates", 1, "menu_item"),
                El("WPS push button", 2, "menu_item")),
            Case("ho2-wifi-P5", 15, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, 0, 0.4, "WifiSettings",
                El("AndroidWifi", 0, "text_block"),
                El("Wi‑Fi calling", 1, "menu_item")),
            Case("ho2-wifi-P6", 16, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, 1, 0.3, "WifiSettings",
                El("Connected", 0, "text_block"),
                El("Use Wi‑Fi", 1, "switch", false)),
            Case("ho2-wifi-P7", 17, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.7, "WifiSettings",
                El("Use Wi‑Fi", 0, "switch", true),
                El("Signal strength", 1, "text_block"),
                El("Wi‑Fi Direct", 2, "menu_item")),
            Case("ho2-wifi-P8", 18, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 1, 0, "WifiSettings",
                El("WLAN", 0, "text"),
                El("WLAN status: Connected", 1, "text_block"),
                El("AndroidWifi", 2, "text_block")),
            Case("ho2-wifi-P9", 19, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.2, "WifiSettings",
                El("Wi‑Fi", 0, "menu_item"),
                El("Saved networks", 1, "menu_item"),
                El("Install certificates", 2, "menu_item")),
            Case("ho2-wifi-P10", 20, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "WifiSettings",
                El("Wi‑Fi", 0, "text"),
                El("Wi‑Fi calling", 1, "menu_item"),
                El("Wi‑Fi Direct", 2, "switch", false),
                El("Connected", 3, "text_block")),
            // ── NetworkAndInternet ────────────────────────────────────────────
            Case("ho2-net-P1", 21, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "NetworkAndInternet",
                El("Network & internet", 0, "text"),
                El("Mobile network", 1, "menu_item"),
                El("Private DNS", 2, "menu_item")),
            Case("ho2-net-P2", 22, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "NetworkAndInternet",
                El("Network & internet", 0, "text"),
                El("Cellular", 1, "menu_item"),
                El("Wi‑Fi", 2, "text"),
                El("Hotspot & tethering", 3, "menu_item")),
            Case("ho2-net-P3", 23, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.55, "NetworkAndInternet",
                El("SIM cards", 0, "menu_item"),
                El("Mobile data", 1, "menu_item"),
                El("Network speed", 2, "text_block")),
            Case("ho2-net-P4", 24, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.95, "NetworkAndInternet",
                El("Private DNS", 0, "menu_item"),
                El("Proxy", 1, "menu_item"),
                El("Emergency alerts", 2, "menu_item")),
            Case("ho2-net-P5", 25, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, 0, 0.4, "NetworkAndInternet",
                El("Cellular", 0, "menu_item"),
                El("Private DNS", 1, "menu_item")),
            Case("ho2-net-P6", 26, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, 1, 0.5, "NetworkAndInternet",
                El("SIM cards", 0, "menu_item"),
                El("Cellular networks", 1, "menu_item")),
            Case("ho2-net-P7", 27, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.75, "NetworkAndInternet",
                El("Airplane mode", 0, "switch", true),
                El("Mobile network", 1, "menu_item"),
                El("SIM cards", 2, "menu_item")),
            Case("ho2-net-P8", 28, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 1, 0, "NetworkAndInternet",
                El("Internet", 0, "text"),
                El("Mobile networks", 1, "menu_item"),
                El("SIM status", 2, "text_block")),
            Case("ho2-net-P9", 29, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.25, "NetworkAndInternet",
                El("Network & internet", 0, "text"),
                El("VPN", 1, "menu_item"),
                El("Private DNS", 2, "menu_item")),
            Case("ho2-net-P10", 30, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "NetworkAndInternet",
                El("Cellular", 0, "menu_item"),
                El("SIM cards", 1, "menu_item"),
                El("Emergency alerts", 2, "menu_item"),
                El("Mobile data", 3, "menu_item")),
            // ── SettingsRoot ──────────────────────────────────────────────────
            Case("ho2-root-P1", 31, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.RealTrace, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "SettingsRoot",
                El("Settings", 0, "text"),
                El("Search settings", 1, "text_block"),
                El("Passwords & accounts", 2, "menu_item")),
            Case("ho2-root-P2", 32, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "SettingsRoot",
                El("Settings", 0, "text"),
                El("Wallpaper & style", 1, "menu_item"),
                El("Display", 2, "menu_item")),
            Case("ho2-root-P3", 33, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.RealTrace, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.65, "SettingsRoot",
                El("Search settings", 0, "text_block"),
                El("Battery", 1, "menu_item"),
                El("100%", 2, "text_block")),
            Case("ho2-root-P4", 34, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.95, "SettingsRoot",
                El("About phone", 0, "menu_item"),
                El("Android version 14", 1, "text_block"),
                El("Security update", 2, "text_block")),
            Case("ho2-root-P5", 35, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, 0, 0.5, "SettingsRoot",
                El("Settings", 0, "text"),
                El("Accessibility", 1, "menu_item")),
            Case("ho2-root-P6", 36, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.RealTrace, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, 1, 0.4, "SettingsRoot",
                El("Battery", 0, "menu_item"),
                El("85%", 1, "text_block")),
            Case("ho2-root-P7", 37, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.7, "SettingsRoot",
                El("Display", 0, "menu_item"),
                El("Adaptive brightness", 1, "switch", true)),
            Case("ho2-root-P8", 38, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 1, 0, "SettingsRoot",
                El("Main settings", 0, "text"),
                El("Network & internet", 1, "menu_item"),
                El("Display & sound", 2, "menu_item")),
            Case("ho2-root-P9", 39, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.2, "SettingsRoot",
                El("Settings", 0, "text"),
                El("User & accounts", 1, "menu_item"),
                El("Accessibility", 2, "menu_item")),
            Case("ho2-root-P10", 40, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.RealTrace, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "SettingsRoot",
                El("Settings", 0, "text"),
                El("Connected devices", 1, "menu_item"),
                El("Bluetooth", 2, "menu_item"),
                El("Pair new device", 3, "menu_item")),
            // ── negatives / hard negatives (24) ───────────────────────────────
            // DeveloperOptions
            Case("ho2-dev-N1", 41, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "DeveloperOptions",
                El("Cellular", 0, "menu_item"),
                El("SIM status", 1, "text_block"),
                El("IMEI", 2, "text_block")),
            Case("ho2-dev-N2", 42, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "DeveloperOptions",
                El("Developer", 0, "text"),
                El("Setup menu", 1, "menu_item"),
                El("Options", 2, "menu_item")),
            Case("ho2-dev-N3", 43, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "DeveloperOptions",
                El("Settings", 0, "text"),
                El("System", 1, "menu_item"),
                El("General", 2, "menu_item"),
                El("Advanced", 3, "menu_item")),
            Case("ho2-dev-N4", 44, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.Unknown, 3, 0, "DeveloperOptions",
                El("", 0, "text_block"),
                El("", 1, "text")),
            Case("ho2-dev-N5", 45, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "DeveloperOptions",
                El("Sound & vibration", 0, "menu_item"),
                El("Do Not Disturb", 1, "menu_item"),
                El("Notifications", 2, "menu_item")),
            Case("ho2-dev-N6", 46, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "DeveloperOptions",
                El("Wallpaper & style", 0, "menu_item"),
                El("Home screen", 1, "menu_item"),
                El("Lock screen", 2, "menu_item")),
            // WifiSettings
            Case("ho2-wifi-N1", 47, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "WifiSettings",
                El("Private DNS", 0, "menu_item"),
                El("Proxy", 1, "menu_item"),
                El("Ethernet", 2, "menu_item")),
            Case("ho2-wifi-N2", 48, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "WifiSettings",
                El("Network", 0, "text"),
                El("Network & internet", 1, "menu_item"),
                El("Sign in to network", 2, "menu_item")),
            Case("ho2-wifi-N3", 49, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "WifiSettings",
                El("Settings", 0, "text"),
                El("System", 1, "menu_item"),
                El("Advanced", 2, "menu_item")),
            Case("ho2-wifi-N4", 50, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.Unknown, 3, 0, "WifiSettings",
                El("", 0, "menu_item"),
                El("", 1, "text_block")),
            Case("ho2-wifi-N5", 51, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "WifiSettings",
                El("Hotspot & tethering", 0, "menu_item"),
                El("USB tethering", 1, "menu_item"),
                El("Bluetooth tethering", 2, "menu_item")),
            Case("ho2-wifi-N6", 52, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.TitleVisible, 1, 0, "DeveloperOptions",
                El("Wi‑Fi", 0, "text"),
                El("AndroidWifi", 1, "text_block"),
                El("Network speed", 2, "text_block"),
                El("Wi‑Fi calling", 3, "menu_item")),
            // NetworkAndInternet
            Case("ho2-net-N1", 53, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "NetworkAndInternet",
                El("Wallpaper", 0, "menu_item"),
                El("Wallpaper & style", 1, "menu_item"),
                El("Home screen", 2, "menu_item")),
            Case("ho2-net-N2", 54, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "NetworkAndInternet",
                El("Mobile", 0, "text"),
                El("Mobile, Wi‑Fi, hotspot", 1, "text_block")),
            Case("ho2-net-N3", 55, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "NetworkAndInternet",
                El("Settings", 0, "text"),
                El("Users", 1, "menu_item"),
                El("Accounts", 2, "menu_item")),
            Case("ho2-net-N4", 56, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.Unknown, 3, 0, "NetworkAndInternet",
                El("", 0, "text"),
                El("", 1, "text_block")),
            Case("ho2-net-N5", 57, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "NetworkAndInternet",
                El("Wi‑Fi", 0, "text"),
                El("Internet", 1, "text_block"),
                El("Network", 2, "text_block")),
            Case("ho2-net-N6", 58, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "SettingsRoot",
                El("Private DNS", 0, "menu_item"),
                El("DNS server", 1, "text_block"),
                El("IP settings", 2, "menu_item")),
            // SettingsRoot
            Case("ho2-root-N1", 59, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "SettingsRoot",
                El("Wi‑Fi", 0, "menu_item"),
                El("Wi‑Fi Direct", 1, "switch", false),
                El("Saved networks", 2, "menu_item")),
            Case("ho2-root-N2", 60, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "SettingsRoot",
                El("Settings", 0, "text"),
                El("Setup assistant", 1, "menu_item"),
                El("Configuration", 2, "menu_item")),
            Case("ho2-root-N3", 61, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "SettingsRoot",
                El("Menu", 0, "text"),
                El("Options", 1, "menu_item"),
                El("Status", 2, "text_block")),
            Case("ho2-root-N4", 62, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.Unknown, 3, 0, "SettingsRoot",
                El("", 0, "text"),
                El("", 1, "menu_item"),
                El("", 2, "text_block")),
            Case("ho2-root-N5", 63, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "SettingsRoot",
                El("Security status", 0, "menu_item"),
                El("Encrypt phone", 1, "menu_item"),
                El("Credential storage", 2, "menu_item")),
            Case("ho2-root-N6", 64, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "SettingsRoot",
                El("Google", 0, "menu_item"),
                El("Account services", 1, "menu_item"),
                El("Synchronization", 2, "menu_item")));

        return new SemanticCorpus(CorpusId, cases)
        {
            Category = SemanticCorpusCategory.Experimental, // excluded from all tuning helpers
        };
    }
}