using System.Collections.Immutable;
using UniClaw.Semantic.Infrastructure.Corpus;
using UniClaw.Runtime.Model;

namespace UniClaw.Semantic.Tests.BenchmarkTests;

/// <summary>
/// ContainerIdentity-heldout-v3 — TRUE independent held-out corpus for the
/// qualification of SEMANTIC_CONTAINER_IDENTITY_PROFILE_V3.
///
/// HYGIENE CONTRACT:
/// - Created AFTER Profile V3 was frozen; Profile V3 and its prototype assets
///   are NOT modified by this gate (receipt pins hashes before the run).
/// - Did NOT participate in any development: feature / embedding / prototype /
///   anchor / margin / evidence-sufficiency / candidate-policy design, V1/V2/V3
///   debugging or hardening.
/// - NOT derived from tuning / former-heldout-v1 / v2 concrete instances: fresh
///   wordings, fresh element combinations, fresh scroll compositions, fresh
///   sibling-page ambiguity, fresh generic settings combinations. New rows
///   (e.g. Simulate secondary displays, Access Point Names, Digital wellbeing,
///   SSID listings) test whether Profile V3 generalizes, not memorizes.
/// - Failure CATEGORIES are reused; concrete instances are fresh (§5).
///
/// Scope: 80 cases = 4 identities × 12 positives + 32 negatives (8 per identity:
/// wrong page, generic+misleading, near-empty, sibling container, text-overlap,
/// structurally similar wrong page, high semantic similarity, previous-identity
/// conflicting observation).
/// </summary>
public static class HeldOutContainerIdentityCorpusV3
{
    /// <summary>Held-out v3 corpus identity.</summary>
    public const string CorpusId = "ContainerIdentity-heldout-v3";

    private static Observation Obs(long seq, params ObservedElement[] elements) =>
        new(elements.ToImmutableArray(), "com.android.settings", seq);

    private static ObservedElement El(string text, int index, string? type = null, bool? switchState = null) =>
        new(text, switchState, index, null, type);

    private static SemanticCase Case(
        string caseId,
        long seq,
        string expectedCandidate,
        string? expectedIdentity,
        SemanticCaseSource source,
        SemanticCaseDifficulty difficulty,
        SemanticViewportState viewport,
        int ambiguity,
        double scroll,
        string? previousVerifiedIdentity,
        params ObservedElement[] elements) =>
        new(
            caseId,
            Obs(seq, elements),
            expectedCandidate,
            expectedIdentity,
            source,
            difficulty)
        {
            PreviousVerifiedIdentity = previousVerifiedIdentity,
            ViewportState = viewport,
            VisibleAnchorState = viewport == SemanticViewportState.TitleVisible
                ? SemanticVisibleAnchorState.AnchorVisible
                : SemanticVisibleAnchorState.AnchorMissing,
            NoiseLevel = difficulty == SemanticCaseDifficulty.Hard ? 1 : 0,
            AmbiguityLevel = ambiguity,
            ScrollPosition = scroll,
        };

    /// <summary>Creates the v3 held-out corpus.</summary>
    public static SemanticCorpus Create() => Build();

    private static SemanticCorpus Build()
    {
        var cases = ImmutableArray.Create(
            // ── DeveloperOptions ×12 positives ────────────────────────────────
            Case("ho3-dev-P1", 1, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "DeveloperOptions",
                El("Developer options", 0, "text"),
                El("Simulate secondary displays", 1, "menu_item"),
                El("Running services", 2, "menu_item")),
            Case("ho3-dev-P2", 2, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "DeveloperOptions",
                El("Developer options", 0, "text"),
                El("Enable GPU debugging layers", 1, "switch", false),
                El("Memory usage", 2, "menu_item")),
            Case("ho3-dev-P3", 3, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.5, "DeveloperOptions",
                El("Running services", 0, "menu_item"),
                El("Simulate secondary displays", 1, "menu_item"),
                El("Wireless debugging", 2, "menu_item")),
            Case("ho3-dev-P4", 4, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.92, "DeveloperOptions",
                El("Pointer location", 0, "switch", true),
                El("Display refresh rate", 1, "menu_item"),
                El("Memory usage", 2, "menu_item")),
            Case("ho3-dev-P5", 5, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, 0, 0.4, "DeveloperOptions",
                El("Developer options", 0, "text"),
                El("Running services", 1, "menu_item")),
            Case("ho3-dev-P6", 6, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 1, 0, "DeveloperOptions",
                El("Developer options", 0, "text")),
            Case("ho3-dev-P7", 7, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 1, 0, "DeveloperOptions",
                El("Developer settings", 0, "text"),
                El("Background process limit", 1, "menu_item")),
            Case("ho3-dev-P8", 8, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 1, 0, "DeveloperOptions",
                El("Simulate secondary displays", 0, "switch", true),
                El("OEM unlocking", 1, "menu_item"),
                El("Developer options", 2, "text")),
            Case("ho3-dev-P9", 9, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 0, 0, "DeveloperOptions",
                El("Select USB configuration", 0, "menu_item"),
                El("Simulate secondary displays", 1, "switch", false),
                El("Developer options", 2, "text"),
                El("Bug report shortcut", 3, "menu_item")),
            Case("ho3-dev-P10", 10, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.85, "DeveloperOptions",
                El("Memory usage", 0, "menu_item"),
                El("Running services", 1, "menu_item"),
                El("Background process limit", 2, "menu_item"),
                El("Show taps", 3, "switch", true)),
            Case("ho3-dev-P11", 11, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 0, 0, "DeveloperOptions",
                El("Developer options", 0, "text"),
                El("Enable demo mode", 1, "switch", true),
                El("Automatic system updates", 2, "switch", true),
                El("Simulate secondary displays", 3, "menu_item")),
            Case("ho3-dev-P12", 12, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.35, "DeveloperOptions",
                El("Wireless debugging", 0, "switch", true),
                El("USB debugging", 1, "menu_item"),
                El("Select USB configuration", 2, "menu_item")),
            // ── WifiSettings ×12 positives ───────────────────────────────────
            Case("ho3-wifi-P1", 13, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "WifiSettings",
                El("Wi‑Fi", 0, "menu_item"),
                El("HomeNet-5G", 1, "menu_item"),
                El("Connected", 2, "text_block"),
                El("AndroidWifi", 3, "text_block")),
            Case("ho3-wifi-P2", 14, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "WifiSettings",
                El("Wi‑Fi", 0, "text"),
                El("CoffeeRoaster3.0", 1, "menu_item"),
                El("OfficeWiFi", 2, "menu_item"),
                El("Use Wi‑Fi", 3, "switch", true)),
            Case("ho3-wifi-P3", 15, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.5, "WifiSettings",
                El("AndroidWifi", 0, "text_block"),
                El("HomeNet-5G", 1, "menu_item"),
                El("Connected", 2, "text_block")),
            Case("ho3-wifi-P4", 16, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.95, "WifiSettings",
                El("Wi‑Fi Direct", 0, "switch", false),
                El("MAC address", 1, "text_block"),
                El("WPS push button", 2, "menu_item")),
            Case("ho3-wifi-P5", 17, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, 0, 0.4, "WifiSettings",
                El("Connected", 0, "text_block"),
                El("Use Wi‑Fi", 1, "switch", true)),
            Case("ho3-wifi-P6", 18, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, 1, 0.3, "WifiSettings",
                El("Use Wi‑Fi", 0, "switch", true)),
            Case("ho3-wifi-P7", 19, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 1, 0, "WifiSettings",
                El("Wi‑Fi", 0, "menu_item"),
                El("WLAN", 1, "text"),
                El("AndroidWifi", 2, "text_block"),
                El("Saved networks", 3, "menu_item")),
            Case("ho3-wifi-P8", 20, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 0, 0, "WifiSettings",
                El("HomeNet-5G", 0, "menu_item"),
                El("Connected", 1, "text_block"),
                El("Signal strength", 2, "text_block"),
                El("Use Wi‑Fi", 3, "switch", false)),
            Case("ho3-wifi-P9", 21, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 0, 0, "WifiSettings",
                El("Wi‑Fi calling", 0, "menu_item"),
                El("Install certificates", 1, "menu_item"),
                El("AndroidWifi", 2, "text_block"),
                El("Wi‑Fi", 3, "menu_item")),
            Case("ho3-wifi-P10", 22, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.8, "WifiSettings",
                El("Wi‑Fi Direct", 0, "switch", true),
                El("WPS push button", 1, "menu_item"),
                El("Add a network", 2, "menu_item")),
            Case("ho3-wifi-P11", 23, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.6, "WifiSettings",
                El("Saved networks", 0, "menu_item"),
                El("HomeNet-5G", 1, "menu_item"),
                El("MAC address", 2, "text_block")),
            Case("ho3-wifi-P12", 24, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "WifiSettings",
                El("Wi‑Fi", 0, "menu_item"),
                El("CoffeeRoaster3.0", 1, "menu_item"),
                El("Use Wi‑Fi", 2, "switch", true),
                El("Connected", 3, "text_block")),
            // ── NetworkAndInternet ×12 positives ──────────────────────────────
            Case("ho3-net-P1", 25, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "NetworkAndInternet",
                El("Network & internet", 0, "text"),
                El("Access Point Names", 1, "menu_item"),
                El("Calling", 2, "menu_item")),
            Case("ho3-net-P2", 26, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "NetworkAndInternet",
                El("Network & internet", 0, "text"),
                El("Cellular", 1, "menu_item"),
                El("Network operator", 2, "text_block"),
                El("SIM cards", 3, "menu_item")),
            Case("ho3-net-P3", 27, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.55, "NetworkAndInternet",
                El("Access Point Names", 0, "menu_item"),
                El("Roaming", 1, "menu_item"),
                El("Mobile data", 2, "menu_item")),
            Case("ho3-net-P4", 28, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.95, "NetworkAndInternet",
                El("Advanced calling", 0, "menu_item"),
                El("Access Point Names", 1, "menu_item"),
                El("Roaming", 2, "menu_item")),
            Case("ho3-net-P5", 29, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, 0, 0.4, "NetworkAndInternet",
                El("SIM cards", 0, "menu_item"),
                El("Calling", 1, "menu_item")),
            Case("ho3-net-P6", 30, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, 1, 0.5, "NetworkAndInternet",
                El("Mobile network", 0, "menu_item")),
            Case("ho3-net-P7", 31, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 1, 0, "NetworkAndInternet",
                El("Internet", 0, "text"),
                El("Mobile data", 1, "switch", true),
                El("SIM status", 2, "text_block")),
            Case("ho3-net-P8", 32, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 0, 0, "NetworkAndInternet",
                El("Network & internet", 0, "text"),
                El("VPN", 1, "menu_item"),
                El("Roaming", 2, "menu_item"),
                El("Calling", 3, "menu_item")),
            Case("ho3-net-P9", 33, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 0, 0, "NetworkAndInternet",
                El("Access Point Names", 0, "menu_item"),
                El("Proxy", 1, "menu_item"),
                El("Mobile networks", 2, "menu_item")),
            Case("ho3-net-P10", 34, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.7, "NetworkAndInternet",
                El("Cellular", 0, "menu_item"),
                El("SIM status", 1, "text_block"),
                El("Data usage", 2, "menu_item"),
                El("Mobile data", 3, "switch", false)),
            Case("ho3-net-P11", 35, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 1, 0, "NetworkAndInternet",
                El("Calling", 0, "menu_item"),
                El("Advanced calling", 1, "switch", true),
                El("Network operator", 2, "text_block")),
            Case("ho3-net-P12", 36, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "NetworkAndInternet",
                El("Internet", 0, "text"),
                El("Access Point Names", 1, "menu_item"),
                El("SIM cards", 2, "menu_item"),
                El("Airplane mode", 3, "switch", true)),
            // ── SettingsRoot ×12 positives ───────────────────────────────────
            Case("ho3-root-P1", 37, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "SettingsRoot",
                El("Settings", 0, "text"),
                El("Search settings", 1, "text_block"),
                El("Digital wellbeing", 2, "menu_item")),
            Case("ho3-root-P2", 38, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "SettingsRoot",
                El("Settings", 0, "text"),
                El("Safety & emergency", 1, "menu_item"),
                El("NFC", 2, "menu_item")),
            Case("ho3-root-P3", 39, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.6, "SettingsRoot",
                El("Storage", 0, "menu_item"),
                El("128 GB used · Free 52 GB", 1, "text_block"),
                El("Battery", 2, "menu_item"),
                El("92%", 3, "text_block")),
            Case("ho3-root-P4", 40, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.95, "SettingsRoot",
                El("Digital wellbeing", 0, "menu_item"),
                El("Parental controls", 1, "menu_item"),
                El("Nearby Share", 2, "menu_item"),
                El("System update", 3, "menu_item")),
            Case("ho3-root-P5", 41, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, 0, 0.4, "SettingsRoot",
                El("Settings", 0, "text"),
                El("Digital wellbeing", 1, "menu_item")),
            Case("ho3-root-P6", 42, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 1, 0, "SettingsRoot",
                El("Settings", 0, "text")),
            Case("ho3-root-P7", 43, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 1, 0, "SettingsRoot",
                El("Main settings", 0, "text"),
                El("Wallpaper & style", 1, "menu_item"),
                El("Battery", 2, "menu_item")),
            Case("ho3-root-P8", 44, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 0, 0, "SettingsRoot",
                El("Settings", 0, "text"),
                El("NFC", 1, "menu_item"),
                El("Nearby Share", 2, "menu_item"),
                El("Bluetooth", 3, "menu_item")),
            Case("ho3-root-P9", 45, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleVisible, 1, 0, "SettingsRoot",
                El("Safety & emergency", 0, "menu_item"),
                El("Emergency information", 1, "text_block"),
                El("Medical information", 2, "menu_item")),
            Case("ho3-root-P10", 46, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.8, "SettingsRoot",
                El("Battery", 0, "menu_item"),
                El("92%", 1, "text_block"),
                El("System update", 2, "menu_item"),
                El("Display", 3, "menu_item")),
            Case("ho3-root-P11", 47, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, 0, 0.7, "SettingsRoot",
                El("Passwords & accounts", 0, "menu_item"),
                El("Digital wellbeing", 1, "menu_item"),
                El("Accessibility", 2, "menu_item")),
            Case("ho3-root-P12", 48, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, 0, 0, "SettingsRoot",
                El("Settings", 0, "text"),
                El("Parental controls", 1, "menu_item"),
                El("Nearby Share", 2, "menu_item"),
                El("Storage", 3, "menu_item")),
            // ── negatives / hard negatives (32) ───────────────────────────────
            Case("ho3-dev-N1", 49, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "DeveloperOptions",
                El("Airplane mode", 0, "switch", true),
                El("Cellular", 1, "menu_item"),
                El("Mobile data", 2, "menu_item")),
            Case("ho3-dev-N2", 50, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 3, 0, "DeveloperOptions",
                El("Developer", 0, "text"),
                El("Settings", 1, "text"),
                El("Menu", 2, "menu_item"),
                El("Options", 3, "menu_item")),
            Case("ho3-dev-N3", 51, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.Unknown, 3, 0, "DeveloperOptions",
                El("", 0, "toggle"),
                El("", 1, "text")),
            Case("ho3-dev-N4", 52, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "DeveloperOptions",
                El("Wi‑Fi", 0, "menu_item"),
                El("Use Wi‑Fi", 1, "switch", false),
                El("AndroidWifi", 2, "text_block")),
            Case("ho3-dev-N5", 53, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "DeveloperOptions",
                El("Developer tips", 0, "text_block"),
                El("System tips", 1, "text_block"),
                El("Status", 2, "text_block")),
            Case("ho3-dev-N6", 54, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "DeveloperOptions",
                El("Battery", 0, "menu_item"),
                El("Storage", 1, "menu_item"),
                El("92%", 2, "text_block")),
            Case("ho3-dev-N7", 55, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "DeveloperOptions",
                El("Debugging", 0, "text"),
                El("Log viewer", 1, "text_block"),
                El("Development tools", 2, "text_block")),
            Case("ho3-dev-N8", 56, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.TitleVisible, 1, 0, "WifiSettings",
                El("Developer options", 0, "text"),
                El("Wireless debugging", 1, "menu_item")),
            Case("ho3-wifi-N1", 57, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "WifiSettings",
                El("Cellular", 0, "menu_item"),
                El("SIM cards", 1, "menu_item"),
                El("Calling", 2, "menu_item")),
            Case("ho3-wifi-N2", 58, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 3, 0, "WifiSettings",
                El("Wi‑Fi settings", 0, "text"),
                El("Network setup", 1, "menu_item"),
                El("Options", 2, "menu_item")),
            Case("ho3-wifi-N3", 59, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.Unknown, 3, 0, "WifiSettings",
                El("", 0, "text"),
                El("", 1, "switch")),
            Case("ho3-wifi-N4", 60, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "WifiSettings",
                El("Airplane mode", 0, "switch", true),
                El("Hotspot & tethering", 1, "menu_item"),
                El("Cellular", 2, "menu_item")),
            Case("ho3-wifi-N5", 61, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "WifiSettings",
                El("Wi‑Fi MAC address", 0, "text_block"),
                El("IP address", 1, "text_block"),
                El("Status", 2, "text_block")),
            Case("ho3-wifi-N6", 62, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "WifiSettings",
                El("Menu", 0, "text"),
                El("Item", 1, "text"),
                El("List", 2, "text_block")),
            Case("ho3-wifi-N7", 63, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "WifiSettings",
                El("Connected devices", 0, "menu_item"),
                El("Bluetooth", 1, "text_block"),
                El("Pairing status", 2, "text_block")),
            Case("ho3-wifi-N8", 64, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.TitleVisible, 1, 0, "DeveloperOptions",
                El("Wi‑Fi", 0, "menu_item"),
                El("AndroidWifi", 1, "text_block"),
                El("Connected", 2, "text_block"),
                El("Use Wi‑Fi", 3, "switch", false)),
            Case("ho3-net-N1", 65, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "NetworkAndInternet",
                El("Sound & vibration", 0, "menu_item"),
                El("Do Not Disturb", 1, "menu_item")),
            Case("ho3-net-N2", 66, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 3, 0, "NetworkAndInternet",
                El("Network", 0, "text"),
                El("Network status", 1, "text_block"),
                El("Settings", 2, "text")),
            Case("ho3-net-N3", 67, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.Unknown, 3, 0, "NetworkAndInternet",
                El("", 0, "text"),
                El("", 1, "text")),
            Case("ho3-net-N4", 68, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "NetworkAndInternet",
                El("Wi‑Fi", 0, "menu_item"),
                El("CoffeeRoaster3.0", 1, "menu_item"),
                El("Connected", 2, "text_block")),
            Case("ho3-net-N5", 69, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "NetworkAndInternet",
                El("Data usage", 0, "menu_item"),
                El("Billing cycle", 1, "menu_item"),
                El("Monthly summary", 2, "text_block")),
            Case("ho3-net-N6", 70, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "NetworkAndInternet",
                El("Menu", 0, "text"),
                El("Settings", 1, "text"),
                El("Advanced", 2, "menu_item")),
            Case("ho3-net-N7", 71, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "NetworkAndInternet",
                El("Profile", 0, "text"),
                El("Proxy settings", 1, "menu_item"),
                El("Server", 2, "text_block")),
            Case("ho3-net-N8", 72, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.TitleVisible, 1, 0, "SettingsRoot",
                El("SIM cards", 0, "menu_item"),
                El("Calling", 1, "menu_item"),
                El("Mobile network", 2, "menu_item")),
            Case("ho3-root-N1", 73, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "SettingsRoot",
                El("Developer options", 0, "text"),
                El("Simulate secondary displays", 1, "menu_item")),
            Case("ho3-root-N2", 74, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 3, 0, "SettingsRoot",
                El("Settings", 0, "text"),
                El("Everything", 1, "menu_item"),
                El("Overview", 2, "text_block")),
            Case("ho3-root-N3", 75, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.Unknown, 3, 0, "SettingsRoot",
                El("", 0, "switch"),
                El("", 1, "text")),
            Case("ho3-root-N4", 76, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "SettingsRoot",
                El("Wi‑Fi calling", 0, "menu_item"),
                El("Wi‑Fi Direct", 1, "switch", false)),
            Case("ho3-root-N5", 77, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "SettingsRoot",
                El("Search", 0, "text_block"),
                El("Search results", 1, "text_block"),
                El("Categories", 2, "menu_item")),
            Case("ho3-root-N6", 78, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "SettingsRoot",
                El("Item", 0, "text"),
                El("Item", 1, "text_block"),
                El("Menu item", 2, "menu_item")),
            Case("ho3-root-N7", 79, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, 2, 0, "DeveloperOptions",
                El("Battery", 0, "menu_item"),
                El("100%", 1, "text_block"),
                El("Charging", 2, "text_block")),
            Case("ho3-root-N8", 80, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.TitleVisible, 1, 0, "WifiSettings",
                El("Settings", 0, "text"),
                El("Digital wellbeing", 1, "menu_item"),
                El("Battery", 2, "menu_item")));

        return new SemanticCorpus(CorpusId, cases)
        {
            Category = SemanticCorpusCategory.Experimental, // excluded from all tuning helpers
        };
    }
}