using System.Collections.Immutable;
using UniClaw.Semantic.Infrastructure.Corpus;
using UniClaw.Runtime.Model;

namespace UniClaw.Semantic.Tests.BenchmarkTests;

/// <summary>
/// HELD-OUT Container Identity corpus — ContainerIdentity-heldout-v1.
///
/// Purpose: independent validation corpus for the frozen
/// BGE_SMALL_CONTAINER_IDENTITY_PROFILE_V1. It MUST NOT be used for tuning.
///
/// Isolation contract (proven by HeldOutValidationTests.T1):
/// - No case id appears in any tuning corpus
///   (DeveloperOptionsBenchmarkCorpus, ContainerIdentityCorpora,
///    ExpandedContainerIdentityCorpora golden+regression+adversarial).
/// - No case shares the same multiset of (text, perception type, switch state)
///   element tuples with any tuning corpus case.
///
/// Coverage: 4 identities x 12 cases = 48 cases, per identity:
///   A x2 Normal (title visible)
///   B x2 Title-offscreen / scroll
///   C x2 Partial observation
///   D x1 Low-information observation (expect abstain)
///   E x2 Similar-page interference (expect abstain)
///   F x3 Hard negative:
///        F1 wrong container (regression family, source Regression)
///        F2 visually/text-overlap similar container (adversarial family)
///        F3 insufficient / empty or near-empty semantic query
///
/// Sources: RealTrace (verbatim or contiguous-subset observations captured in
/// committed traces: openspec/.../uitars-bench/truth.json
/// root-top / root-scrolled / accessibility / display-child, and the Wi-Fi /
/// DeveloperOptions traces documented in docs/experiments/qwen2.5-vl-local-preview.md),
/// Manual (authored from real Settings-app knowledge, possibly derived from a
/// real trace with edits), Synthetic (adversarial constructions), Regression
/// (new variants of documented historical failure families — never verbatim
/// tuning cases).
/// </summary>
public static class HeldOutContainerIdentityCorpus
{
    /// <summary>Held-out corpus identity, referenced by the frozen profile.</summary>
    public const string CorpusId = "ContainerIdentity-heldout-v1";

    private static Observation Obs(long seq, params ObservedElement[] elements) =>
        new(elements.ToImmutableArray(), "com.android.settings", seq);

    private static ObservedElement El(string text, int index, string? type = null, bool? switchState = null) =>
        new(text, switchState, index, null, type);

    private static SemanticCase Case(
        string caseId,
        long seq,
        string expectedCandidate,
        string? expectedIdentity,
        SemanticCaseSource source,
        SemanticCaseDifficulty difficulty,
        SemanticViewportState viewport,
        SemanticVisibleAnchorState anchor,
        int noise,
        int ambiguity,
        double scroll,
        string? previousVerifiedIdentity,
        params ObservedElement[] elements) =>
        new(
            caseId,
            Obs(seq, elements),
            expectedCandidate,
            expectedIdentity,
            source,
            difficulty)
        {
            PreviousVerifiedIdentity = previousVerifiedIdentity,
            ViewportState = viewport,
            VisibleAnchorState = anchor,
            NoiseLevel = noise,
            AmbiguityLevel = ambiguity,
            ScrollPosition = scroll,
        };

    /// <summary>Creates the held-out corpus.</summary>
    public static SemanticCorpus Create() => Build();

    private static SemanticCorpus Build()
    {
        var cases = ImmutableArray.Create(
            // ── DeveloperOptions ─────────────────────────────────────────────
            // A: Normal, title visible
            Case("ho-dev-A1", 1, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.RealTrace, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, SemanticVisibleAnchorState.AnchorVisible,
                0, 0, 0, "DeveloperOptions",
                El("Developer options", 0, "text"),
                El("Enable demo mode", 1, "menu_item"),
                El("Show demo mode", 2, "menu_item"),
                El("Automatic system updates", 3, "switch", false)),
            Case("ho-dev-A2", 2, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, SemanticVisibleAnchorState.AnchorVisible,
                0, 0, 0, "DeveloperOptions",
                El("Developer options", 0, "text"),
                El("Automatic system updates", 1, "switch", true),
                El("Background process limit", 2, "menu_item")),
            // B: Title offscreen / scroll
            Case("ho-dev-B1", 3, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, SemanticVisibleAnchorState.AnchorMissing,
                0, 0, 0.45, "DeveloperOptions",
                El("Show demo mode", 0, "menu_item"),
                El("Automatic system updates", 1, "switch", true),
                El("Don't keep activities", 2, "menu_item")),
            Case("ho-dev-B2", 4, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, SemanticVisibleAnchorState.AnchorMissing,
                0, 0, 0.85, "DeveloperOptions",
                El("Automatic system updates", 0, "switch", false),
                El("Don't keep activities", 1, "menu_item"),
                El("Background process limit", 2, "menu_item"),
                El("Bug report shortcut", 3, "menu_item")),
            // C: Partial observation
            Case("ho-dev-C1", 5, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, SemanticVisibleAnchorState.AnchorMissing,
                1, 0, 0.2, "DeveloperOptions",
                El("Enable demo mode", 0, "menu_item"),
                El("Show demo mode", 1, "menu_item")),
            Case("ho-dev-C2", 6, "DeveloperOptions", "DeveloperOptions",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, SemanticVisibleAnchorState.AnchorMissing,
                1, 1, 0.6, "DeveloperOptions",
                El("Automatic system updates", 0, "switch", true)),
            // D: Low-information observation (expect abstain)
            Case("ho-dev-D1", 7, "None", null,
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Hard,
                SemanticViewportState.TitleOffscreen, SemanticVisibleAnchorState.AnchorMissing,
                1, 2, 0.5, "DeveloperOptions",
                El("System", 0, "menu_item")),
            // E: Similar-page interference (expect abstain)
            Case("ho-dev-E1", 8, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, SemanticVisibleAnchorState.AnchorMissing,
                1, 2, 0, "Security",
                El("Enable demo mode", 0, "menu_item"),
                El("System UI demo mode", 1, "menu_item"),
                El("Security", 2, "menu_item")),
            Case("ho-dev-E2", 9, "None", null,
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, SemanticVisibleAnchorState.AnchorMissing,
                1, 2, 0, "Security",
                El("Developer options", 0, "text"),
                El("Security", 1, "text")),
            // F1: wrong container (Regression: documented Data-usage wrong-page
            //     failure family, new content), F2 accessibility page = real
            //     wrong-container trace, F3 near-empty semantic query.
            Case("ho-dev-F1", 10, "None", null,
                SemanticCaseSource.Regression, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, SemanticVisibleAnchorState.AnchorMissing,
                1, 2, 0, "DeveloperOptions",
                El("Data usage", 0, "menu_item"),
                El("Cellular data", 1, "menu_item"),
                El("Wi-Fi data usage", 2, "menu_item")),
            Case("ho-dev-F2", 11, "None", null,
                SemanticCaseSource.RealTrace, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, SemanticVisibleAnchorState.AnchorMissing,
                1, 2, 0, "DeveloperOptions",
                El("Accessibility", 0, "text"),
                El("Display", 1, "menu_item"),
                El("Color and motion", 2, "menu_item")),
            Case("ho-dev-F3", 12, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.Unknown, SemanticVisibleAnchorState.Unknown,
                2, 3, 0, "DeveloperOptions",
                El("", 0, "text")),
            // ── WifiSettings ─────────────────────────────────────────────────
            Case("ho-wifi-A1", 13, "WifiSettings", "WifiSettings",
                SemanticCaseSource.RealTrace, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, SemanticVisibleAnchorState.AnchorVisible,
                0, 0, 0, "WifiSettings",
                El("Wi-Fi", 0, "menu_item"),
                El("Connected", 1, "text_block"),
                El("AndroidWifi", 2, "text_block"),
                El("Use Wi-Fi", 3, "switch", true)),
            Case("ho-wifi-A2", 14, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, SemanticVisibleAnchorState.AnchorVisible,
                0, 0, 0, "WifiSettings",
                El("Wi-Fi", 0, "text"),
                El("Network & internet", 1, "menu_item"),
                El("Saved networks", 2, "menu_item")),
            Case("ho-wifi-B1", 15, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, SemanticVisibleAnchorState.AnchorMissing,
                0, 0, 0.7, "WifiSettings",
                El("AndroidWifi", 0, "text_block"),
                El("Connected", 1, "text_block"),
                El("Signal strength", 2, "text_block")),
            Case("ho-wifi-B2", 16, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, SemanticVisibleAnchorState.AnchorMissing,
                0, 0, 0.9, "WifiSettings",
                El("Saved networks", 0, "menu_item"),
                El("Add network", 1, "menu_item"),
                El("Wi-Fi preferences", 2, "menu_item")),
            Case("ho-wifi-C1", 17, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, SemanticVisibleAnchorState.AnchorMissing,
                1, 0, 0.4, "WifiSettings",
                El("AndroidWifi", 0, "text_block"),
                El("Use Wi-Fi", 1, "switch", true)),
            Case("ho-wifi-C2", 18, "WifiSettings", "WifiSettings",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, SemanticVisibleAnchorState.AnchorMissing,
                1, 1, 0.3, "WifiSettings",
                El("Connected", 0, "text_block")),
            Case("ho-wifi-D1", 19, "None", null,
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Hard,
                SemanticViewportState.TitleOffscreen, SemanticVisibleAnchorState.AnchorMissing,
                1, 2, 0.2, "WifiSettings",
                El("Network & internet", 0, "menu_item")),
            Case("ho-wifi-E1", 20, "None", null,
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, SemanticVisibleAnchorState.AnchorMissing,
                1, 2, 0, "NetworkAndInternet",
                El("Hotspot & tethering", 0, "menu_item"),
                El("Mobile hotspot", 1, "menu_item"),
                El("Wi-Fi sharing", 2, "menu_item")),
            Case("ho-wifi-E2", 21, "None", null,
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, SemanticVisibleAnchorState.AnchorMissing,
                1, 2, 0, "NetworkAndInternet",
                El("Wi-Fi", 0, "text"),
                El("Ethernet", 1, "menu_item"),
                El("VPN", 2, "menu_item")),
            Case("ho-wifi-F1", 22, "None", null,
                SemanticCaseSource.Regression, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, SemanticVisibleAnchorState.AnchorMissing,
                1, 2, 0, "WifiSettings",
                El("SIM cards", 0, "menu_item"),
                El("Mobile data", 1, "menu_item"),
                El("Data usage", 2, "menu_item")),
            Case("ho-wifi-F2", 23, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, SemanticVisibleAnchorState.AnchorMissing,
                1, 2, 0, "NetworkAndInternet",
                El("Wi-Fi", 0, "text"),
                El("Network & internet", 1, "text")),
            Case("ho-wifi-F3", 24, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.TitleVisible, SemanticVisibleAnchorState.AnchorVisible,
                0, 1, 0, "DeveloperOptions",
                El("AndroidWifi", 0, "text_block"),
                El("Connected", 1, "text_block"),
                El("Use Wi-Fi", 2, "switch", false)),
            // ── NetworkAndInternet ────────────────────────────────────────────
            Case("ho-net-A1", 25, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, SemanticVisibleAnchorState.AnchorVisible,
                0, 0, 0, "NetworkAndInternet",
                El("Network & internet", 0, "text"),
                El("Airplane mode", 1, "menu_item"),
                El("Cellular", 2, "menu_item")),
            Case("ho-net-A2", 26, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, SemanticVisibleAnchorState.AnchorVisible,
                0, 0, 0, "NetworkAndInternet",
                El("Network & internet", 0, "text"),
                El("Wi-Fi", 1, "text"),
                El("Hotspot & tethering", 2, "menu_item")),
            Case("ho-net-B1", 27, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, SemanticVisibleAnchorState.AnchorMissing,
                0, 0, 0.8, "NetworkAndInternet",
                El("Cellular", 0, "menu_item"),
                El("SIM cards", 1, "menu_item"),
                El("Mobile data", 2, "menu_item")),
            Case("ho-net-B2", 28, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, SemanticVisibleAnchorState.AnchorMissing,
                0, 0, 0.95, "NetworkAndInternet",
                El("Mobile data", 0, "menu_item"),
                El("Data usage", 1, "menu_item"),
                El("Emergency alerts", 2, "menu_item")),
            Case("ho-net-C1", 29, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, SemanticVisibleAnchorState.AnchorMissing,
                1, 0, 0.5, "NetworkAndInternet",
                El("Cellular", 0, "menu_item"),
                El("Airplane mode", 1, "menu_item")),
            Case("ho-net-C2", 30, "NetworkAndInternet", "NetworkAndInternet",
                SemanticCaseSource.RealTrace, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, SemanticVisibleAnchorState.AnchorMissing,
                1, 0, 0.6, "NetworkAndInternet",
                El("SIM cards", 0, "menu_item"),
                El("VPN", 1, "menu_item")),
            Case("ho-net-D1", 31, "None", null,
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Hard,
                SemanticViewportState.TitleOffscreen, SemanticVisibleAnchorState.AnchorMissing,
                2, 2, 0.4, "NetworkAndInternet",
                El("Airplane mode", 0, "menu_item")),
            Case("ho-net-E1", 32, "None", null,
                SemanticCaseSource.RealTrace, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, SemanticVisibleAnchorState.AnchorMissing,
                1, 2, 0, "NetworkAndInternet",
                El("Network & internet", 0, "menu_item"),
                El("Connected devices", 1, "menu_item"),
                El("Apps", 2, "menu_item")),
            Case("ho-net-E2", 33, "None", null,
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, SemanticVisibleAnchorState.AnchorMissing,
                1, 2, 0, "NetworkAndInternet",
                El("Network & internet", 0, "text"),
                El("IP address", 1, "text_block"),
                El("MAC address", 2, "text_block")),
            Case("ho-net-F1", 34, "None", null,
                SemanticCaseSource.Regression, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, SemanticVisibleAnchorState.AnchorMissing,
                1, 2, 0, "NetworkAndInternet",
                El("Data usage", 0, "menu_item"),
                El("Data saver", 1, "menu_item"),
                El("Billing cycle", 2, "menu_item")),
            Case("ho-net-F2", 35, "None", null,
                SemanticCaseSource.RealTrace, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, SemanticVisibleAnchorState.AnchorMissing,
                1, 2, 0, "NetworkAndInternet",
                El("Display", 0, "text"),
                El("Brightness", 1, "menu_item"),
                El("Screen timeout", 2, "menu_item")),
            Case("ho-net-F3", 36, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.Unknown, SemanticVisibleAnchorState.Unknown,
                2, 3, 0, "NetworkAndInternet",
                El("", 0, "text"),
                El("", 1, "menu_item")),
            // ── SettingsRoot ─────────────────────────────────────────────────
            Case("ho-root-A1", 37, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.RealTrace, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, SemanticVisibleAnchorState.AnchorVisible,
                0, 0, 0, "SettingsRoot",
                El("Settings", 0, "text"),
                El("Search settings", 1, "text_block"),
                El("Network & internet", 2, "menu_item")),
            Case("ho-root-A2", 38, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.RealTrace, SemanticCaseDifficulty.Easy,
                SemanticViewportState.TitleVisible, SemanticVisibleAnchorState.AnchorVisible,
                0, 0, 0, "SettingsRoot",
                El("Settings", 0, "text"),
                El("Search settings", 1, "text_block"),
                El("Connected devices", 2, "menu_item"),
                El("Bluetooth, pairing", 3, "text_block"),
                El("Apps", 4, "menu_item")),
            Case("ho-root-B1", 39, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.RealTrace, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, SemanticVisibleAnchorState.AnchorMissing,
                0, 0, 0.7, "SettingsRoot",
                El("Battery", 0, "menu_item"),
                El("100%", 1, "text_block"),
                El("Storage", 2, "menu_item"),
                El("38% used - 9.96 GB free", 3, "text_block"),
                El("Sound & vibration", 4, "menu_item")),
            Case("ho-root-B2", 40, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.TitleOffscreen, SemanticVisibleAnchorState.AnchorMissing,
                0, 0, 0.95, "SettingsRoot",
                El("Display", 0, "menu_item"),
                El("Dark theme, font size, brightness", 1, "text_block"),
                El("Wallpaper", 2, "menu_item"),
                El("Home, lock screen", 3, "text_block"),
                El("Accessibility", 4, "menu_item")),
            Case("ho-root-C1", 41, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, SemanticVisibleAnchorState.AnchorMissing,
                1, 0, 0.3, "SettingsRoot",
                El("Settings", 0, "text"),
                El("Battery", 1, "menu_item")),
            Case("ho-root-C2", 42, "SettingsRoot", "SettingsRoot",
                SemanticCaseSource.RealTrace, SemanticCaseDifficulty.Medium,
                SemanticViewportState.Partial, SemanticVisibleAnchorState.AnchorMissing,
                1, 0, 0.4, "SettingsRoot",
                El("Notifications", 0, "menu_item"),
                El("Notification history, conversations", 1, "text_block")),
            Case("ho-root-D1", 43, "None", null,
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Hard,
                SemanticViewportState.Partial, SemanticVisibleAnchorState.AnchorMissing,
                1, 3, 0.6, "SettingsRoot",
                El("Dark theme", 0, "menu_item"),
                El("Brightness level", 1, "text_block")),
            Case("ho-root-E1", 44, "None", null,
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, SemanticVisibleAnchorState.AnchorMissing,
                1, 2, 0, "SettingsRoot",
                El("System", 0, "menu_item"),
                El("About phone", 1, "menu_item"),
                El("Reset options", 2, "menu_item")),
            Case("ho-root-E2", 45, "None", null,
                SemanticCaseSource.Manual, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, SemanticVisibleAnchorState.AnchorMissing,
                1, 2, 0, "Security",
                El("Settings", 0, "text"),
                El("Privacy", 1, "menu_item"),
                El("Security & privacy", 2, "menu_item"),
                El("System", 3, "menu_item")),
            Case("ho-root-F1", 46, "None", null,
                SemanticCaseSource.Regression, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, SemanticVisibleAnchorState.AnchorMissing,
                1, 2, 0, "SettingsRoot",
                El("Developer options", 0, "menu_item"),
                El("Background process limit", 1, "menu_item")),
            Case("ho-root-F2", 47, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.WrongPage, SemanticVisibleAnchorState.AnchorMissing,
                1, 2, 0, "SettingsRoot",
                El("Settings", 0, "text"),
                El("Network & internet", 1, "text"),
                El("Security", 2, "text")),
            Case("ho-root-F3", 48, "None", null,
                SemanticCaseSource.Synthetic, SemanticCaseDifficulty.Hard,
                SemanticViewportState.Unknown, SemanticVisibleAnchorState.Unknown,
                3, 3, 0, "SettingsRoot"));

        return new SemanticCorpus(CorpusId, cases)
        {
            // Not Golden/Regression/Adversarial-for-tuning: held-out validation
            // samples are exploration by category; they are excluded from every
            // benchmark that selects tuning categories.
            Category = SemanticCorpusCategory.Experimental,
        };
    }
}