using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using UniClaw.Kernel.Runtime;

namespace UniClaw.Agent.Dsh;

/// <summary>Generated protocol artifact. The schema is built from the public .NET
/// records at runtime/build time; no JSON Schema copy is used as an authority.</summary>
public sealed record ProductProtocolSchema(
    string ProtocolVersion,
    string SchemaVersion,
    string SchemaHash,
    string Json)
{
    public static ProductProtocolSchema Current => ProductProtocolSchemaGenerator.Generate();
}

public static class ProductProtocolSchemaGenerator
{
    private static readonly Type[] AuthorityTypes =
    {
        typeof(AgentDecisionContext), typeof(AgentDecision), typeof(AgentActionProposal),
        typeof(AgentActionStep), typeof(AgentNoActionProposal), typeof(ObserveSpec),
        typeof(PolicyProposal), typeof(PolicyPredicate), typeof(PolicyActionTemplate),
        typeof(PolicyGuard), typeof(ClaimSummary), typeof(AgentObligationView),
        typeof(ElementSummary), typeof(ScreenSummary), typeof(ConsultationProgress),
        typeof(ConsultationBudget), typeof(CompletionEvidence), typeof(PolicyProgressState),
    };

    public static ProductProtocolSchema Generate()
    {
        var builder = new ReflectionSchemaBuilder();
        foreach (var type in AuthorityTypes)
            builder.EnsureDefinition(type);

        var root = new JsonObject
        {
            ["$schema"] = "https://json-schema.org/draft/2020-12/schema",
            ["$id"] = "https://uniclaw.dev/schemas/agent-protocol/v1",
            ["title"] = "UniClaw Agent Product Protocol",
            ["type"] = "object",
            ["properties"] = new JsonObject
            {
                ["protocolVersion"] = new JsonObject { ["const"] = ProductProtocolVersions.ProtocolVersion },
                ["schemaVersion"] = new JsonObject { ["const"] = ProductProtocolVersions.SchemaVersion },
                ["agentDecisionContext"] = Ref(typeof(AgentDecisionContext)),
                ["agentDecision"] = Ref(typeof(AgentDecision)),
                ["submit_decision"] = new JsonObject
                {
                    ["type"] = "object",
                    ["properties"] = new JsonObject { ["decision"] = Ref(typeof(AgentDecision)) },
                    ["required"] = new JsonArray("decision"),
                    ["additionalProperties"] = false,
                },
            },
            ["required"] = new JsonArray("protocolVersion", "schemaVersion"),
            ["additionalProperties"] = false,
            ["$defs"] = builder.Definitions,
        };

        var canonical = Canonicalize(root);
        var json = canonical.ToJsonString(new JsonSerializerOptions { WriteIndented = false });
        var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(json))).ToLowerInvariant();
        return new ProductProtocolSchema(ProductProtocolVersions.ProtocolVersion,
            ProductProtocolVersions.SchemaVersion, hash, json);
    }

    public static void WriteArtifact(string path)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);
        var schema = Generate();
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);
        File.WriteAllText(path, schema.Json + Environment.NewLine, new UTF8Encoding(false));
    }

    /// <summary>Emit TypeScript from the generated JSON Schema.  The emitter has
    /// no product union declarations of its own: adding a .NET record or union
    /// member changes the schema first and the declaration follows it.</summary>
    public static string GenerateTypeScript()
    {
        using var document = JsonDocument.Parse(Generate().Json);
        var definitions = document.RootElement.GetProperty("$defs");
        var builder = new StringBuilder("// Generated by ProductProtocolSchemaGenerator. DO NOT EDIT.\n\n");
        foreach (var definition in definitions.EnumerateObject().OrderBy(static p => p.Name,
                     StringComparer.Ordinal))
        {
            builder.Append("export type ").Append(definition.Name).Append(" = ")
                .Append(TypeScriptFor(definition.Value)).AppendLine(";");
        }

        var properties = document.RootElement.GetProperty("properties");
        builder.Append("export type SubmitDecision = ")
            .Append(TypeScriptFor(properties.GetProperty("submit_decision"))).AppendLine(";");
        builder.Append("export type ProductProtocolEnvelope = ")
            .Append(TypeScriptFor(document.RootElement)).AppendLine(";");

        return builder.ToString();
    }

    private static string TypeScriptFor(JsonElement schema)
    {
        if (schema.TryGetProperty("$ref", out var reference))
            return reference.GetString()!.Split('/').Last();
        if (schema.TryGetProperty("const", out var constant))
            return constant.ValueKind == JsonValueKind.String
                ? $"'{constant.GetString()}'"
                : constant.GetRawText();
        if (schema.TryGetProperty("oneOf", out var variants))
            return string.Join(" | ", variants.EnumerateArray().Select(TypeScriptFor));
        if (schema.TryGetProperty("enum", out var values))
            return string.Join(" | ", values.EnumerateArray().Select(v => $"'{v.GetString()}'"));
        if (schema.TryGetProperty("type", out var type))
        {
            switch (type.GetString())
            {
                case "string":
                    return "string";
                case "integer":
                case "number": return "number";
                case "boolean": return "boolean";
                case "array": return $"Array<{TypeScriptFor(schema.GetProperty("items"))}>";
                case "object":
                    var properties = schema.TryGetProperty("properties", out var props)
                        ? props : default;
                    var required = schema.TryGetProperty("required", out var req)
                        ? req.EnumerateArray().Select(v => v.GetString()!).ToHashSet(StringComparer.Ordinal)
                        : new HashSet<string>(StringComparer.Ordinal);
                    var members = properties.ValueKind == JsonValueKind.Object
                        ? properties.EnumerateObject().Select(p =>
                            $"{p.Name}{(required.Contains(p.Name) ? "" : "?")}: {TypeScriptFor(p.Value)}")
                        : Enumerable.Empty<string>();
                    if (schema.TryGetProperty("additionalProperties", out var additional)
                        && additional.ValueKind != JsonValueKind.False)
                    {
                        var value = additional.ValueKind == JsonValueKind.Object
                            ? TypeScriptFor(additional) : "unknown";
                        members = members.Append($"[key: string]: {value}");
                    }
                    return $"{{ {string.Join("; ", members)} }}";
            }
        }
        return "unknown";
    }

    public static void WriteTypeScriptArtifact(string path)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);
        File.WriteAllText(path, GenerateTypeScript(), new UTF8Encoding(false));
    }

    private static JsonObject Ref(Type type) => new() { ["$ref"] = $"#/$defs/{type.Name}" };

    private static JsonNode Canonicalize(JsonNode node)
    {
        if (node is JsonObject obj)
        {
            var sorted = new JsonObject();
            foreach (var property in obj.OrderBy(static p => p.Key, StringComparer.Ordinal))
                sorted[property.Key] = property.Value is null ? null : Canonicalize(property.Value);
            return sorted;
        }
        if (node is JsonArray array)
        {
            var result = new JsonArray();
            foreach (var child in array)
                result.Add(child is null ? null : Canonicalize(child));
            return result;
        }
        return node.DeepClone();
    }

    private sealed class ReflectionSchemaBuilder
    {
        private readonly HashSet<Type> _building = new();
        public JsonObject Definitions { get; } = new();

        public void EnsureDefinition(Type type)
        {
            type = Unwrap(type);
            if (IsScalar(type) || IsCollection(type) || type == typeof(JsonElement))
                return;
            if (Definitions.ContainsKey(type.Name) || !_building.Add(type))
                return;

            JsonNode schema;
            if (type == typeof(AgentDecision))
            {
                schema = new JsonObject
                {
                    ["oneOf"] = new JsonArray(
                        new JsonObject
                        {
                            ["type"] = "object", ["properties"] = new JsonObject
                            {
                                ["kind"] = new JsonObject { ["const"] = "act" },
                                ["decisionId"] = new JsonObject { ["type"] = "string" },
                                ["proposal"] = Ref(typeof(AgentActionProposal)),
                            }, ["required"] = new JsonArray("kind", "decisionId", "proposal"),
                            ["additionalProperties"] = false,
                        },
                        new JsonObject
                        {
                            ["type"] = "object", ["properties"] = new JsonObject
                            {
                                ["kind"] = new JsonObject { ["const"] = "policy" },
                                ["decisionId"] = new JsonObject { ["type"] = "string" },
                                ["proposal"] = Ref(typeof(PolicyProposal)),
                            }, ["required"] = new JsonArray("kind", "decisionId", "proposal"),
                            ["additionalProperties"] = false,
                        },
                        new JsonObject
                        {
                            ["type"] = "object", ["properties"] = new JsonObject
                            {
                                ["kind"] = new JsonObject { ["const"] = "noAction" },
                                ["decisionId"] = new JsonObject { ["type"] = "string" },
                                ["proposal"] = Ref(typeof(AgentNoActionProposal)),
                            }, ["required"] = new JsonArray("kind", "decisionId", "proposal"),
                            ["additionalProperties"] = false,
                        },
                        new JsonObject
                        {
                            ["type"] = "object", ["properties"] = new JsonObject
                            {
                                ["kind"] = new JsonObject { ["const"] = "defer" },
                                ["decisionId"] = new JsonObject { ["type"] = "string" },
                                ["spec"] = Ref(typeof(ObserveSpec)),
                            }, ["required"] = new JsonArray("kind", "decisionId", "spec"),
                            ["additionalProperties"] = false,
                        })
                };
            }
            else if (type == typeof(PolicyPredicate))
            {
                schema = new JsonObject
                {
                    ["oneOf"] = new JsonArray(
                        new JsonObject { ["type"] = "object", ["properties"] = new JsonObject
                        {
                            ["kind"] = new JsonObject { ["const"] = "claimEquals" },
                            ["subject"] = new JsonObject { ["type"] = "string" },
                            ["value"] = new JsonObject { ["type"] = "string" },
                        }, ["required"] = new JsonArray("kind", "subject", "value"),
                            ["additionalProperties"] = false },
                        new JsonObject { ["type"] = "object", ["properties"] = new JsonObject
                        {
                            ["kind"] = new JsonObject { ["const"] = "claimInSet" },
                            ["subject"] = new JsonObject { ["type"] = "string" },
                            ["values"] = new JsonObject { ["type"] = "array", ["items"] = new JsonObject { ["type"] = "string" } },
                        }, ["required"] = new JsonArray("kind", "subject", "values"),
                            ["additionalProperties"] = false })
                };
            }
            else if (type == typeof(PolicyGuard))
            {
                schema = new JsonObject
                {
                    ["oneOf"] = new JsonArray(new JsonObject { ["type"] = "object", ["properties"] = new JsonObject
                    {
                        ["kind"] = new JsonObject { ["const"] = "observationUnchanged" },
                        ["subject"] = new JsonObject { ["type"] = "string" },
                        ["afterRounds"] = new JsonObject { ["type"] = "integer", ["minimum"] = 1 },
                    }, ["required"] = new JsonArray("kind", "subject", "afterRounds"),
                        ["additionalProperties"] = false })
                };
            }
            else if (type.IsAbstract)
            {
                var variants = type.GetNestedTypes(BindingFlags.Public)
                    .Where(static t => !t.IsAbstract)
                    .OrderBy(static t => t.Name, StringComparer.Ordinal)
                    .Select(t =>
                    {
                        EnsureDefinition(t);
                        return Ref(t);
                    }).ToArray();
                schema = new JsonObject
                {
                    ["oneOf"] = new JsonArray(variants),
                };
            }
            else if (type.IsEnum)
            {
                schema = new JsonObject
                {
                    ["type"] = "string",
                    ["enum"] = new JsonArray(Enum.GetNames(type).Order(StringComparer.Ordinal)
                        .Select(static name => JsonValue.Create(name)).ToArray()),
                };
            }
            else
            {
                var properties = new JsonObject();
                var required = new JsonArray();
                var nullability = new NullabilityInfoContext();
                foreach (var property in type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
                    .Where(static p => p.GetMethod is not null)
                    .OrderBy(static p => p.Name, StringComparer.Ordinal))
                {
                    properties[ToCamelCase(property.Name)] = SchemaFor(property.PropertyType);
                    var propertyNullability = nullability.Create(property);
                    if (Nullable.GetUnderlyingType(property.PropertyType) is null
                        && propertyNullability.ReadState != NullabilityState.Nullable)
                        required.Add(ToCamelCase(property.Name));
                }
                schema = new JsonObject
                {
                    ["type"] = "object",
                    ["properties"] = properties,
                    ["additionalProperties"] = false,
                };
                if (required.Count > 0)
                    ((JsonObject)schema)["required"] = required;
            }

            _building.Remove(type);
            Definitions[type.Name] = schema;
        }

        private JsonNode SchemaFor(Type type)
        {
            type = Unwrap(type);
            if (type == typeof(string) || type == typeof(Guid) || type == typeof(DateTimeOffset))
                return new JsonObject { ["type"] = "string" };
            if (type == typeof(bool)) return new JsonObject { ["type"] = "boolean" };
            if (type == typeof(int) || type == typeof(long) || type == typeof(double) || type == typeof(decimal))
                return new JsonObject { ["type"] = "number" };
            if (type == typeof(JsonElement)) return new JsonObject();
            if (type.IsGenericType && (type.GetGenericTypeDefinition() == typeof(IReadOnlyDictionary<,>)
                || type.GetGenericTypeDefinition() == typeof(IDictionary<,>)
                || type.GetGenericTypeDefinition() == typeof(Dictionary<,>)))
            {
                return new JsonObject { ["type"] = "object", ["additionalProperties"] =
                    SchemaFor(type.GetGenericArguments()[1]) };
            }
            if (type.IsEnum)
            {
                return new JsonObject
                {
                    ["type"] = "string",
                    ["enum"] = new JsonArray(Enum.GetNames(type).Order(StringComparer.Ordinal)
                        .Select(static name => JsonValue.Create(name)).ToArray()),
                };
            }
            if (IsCollection(type))
            {
                var element = type.IsArray ? type.GetElementType()! : type.GetGenericArguments().Last();
                return new JsonObject { ["type"] = "array", ["items"] = SchemaFor(element) };
            }
            EnsureDefinition(type);
            return Ref(type);
        }

        private static Type Unwrap(Type type) => Nullable.GetUnderlyingType(type) ?? type;

        private static bool IsScalar(Type type) => type.IsPrimitive || type.IsEnum
            || type == typeof(string) || type == typeof(Guid) || type == typeof(DateTimeOffset)
            || type == typeof(decimal) || type == typeof(JsonElement);

        private static bool IsCollection(Type type) => type.IsArray
            || (type.IsGenericType && (typeof(System.Collections.IEnumerable).IsAssignableFrom(type)
                || type.GetGenericTypeDefinition() == typeof(IReadOnlySet<>)));

        private static string ToCamelCase(string name) => string.IsNullOrEmpty(name)
            ? name
            : char.ToLowerInvariant(name[0]) + name[1..];
    }
}
